import {test,expect,type Page} from '@playwright/test';
async function open(page:Page){await page.goto('/');await page.getByTitle('Mettre en pause (Espace)').click();await page.getByRole('button',{name:'Sauvegarder',exact:true}).click();const saved=await page.evaluate(()=>localStorage.getItem('swarm-save'));await page.getByRole('button',{name:'SWARM ARENA',exact:true}).click();return saved;}
const algorithms=['nearest','balanced','eco','priority','guardian','fairness'];
test('all six independent strategies, presets, validation, locked pause, reset and preserved main game',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const saved=await open(page);for(const id of algorithms){await page.getByLabel('Stratégie équipe A').selectOption(id);await expect(page.getByTestId('arena-nearest')).toHaveAttribute('data-strategy',id);await page.getByLabel('Stratégie équipe B').selectOption(id);await expect(page.getByTestId('arena-balanced')).toHaveAttribute('data-strategy',id);}
 for(const id of ['batteries','urgent','energy','fleet']){await page.getByLabel('Conditions initiales').selectOption(id);await expect(page.getByTestId('duel')).toHaveAttribute('data-tick','0');}
 await page.getByLabel('Nombre de commandes').fill('201');await expect(page.getByRole('alert')).toContainText('1 et 200');await expect(page.getByRole('button',{name:'Lancer le duel',exact:true})).toBeDisabled();await page.getByLabel('Nombre de commandes').fill('25');await page.getByLabel('Stratégie équipe A').selectOption('guardian');await page.getByLabel('Stratégie équipe B').selectOption('fairness');await page.getByRole('button',{name:'×10',exact:true}).click();await page.getByRole('button',{name:'Lancer le duel',exact:true}).click();await expect.poll(async()=>Number(await page.getByTestId('duel').getAttribute('data-tick'))).toBeGreaterThan(4);await page.getByRole('button',{name:'Pause du duel',exact:true}).click();for(const name of ['Stratégie équipe A','Stratégie équipe B','Conditions initiales','Nombre de commandes','Durée du duel'])await expect(page.getByLabel(name)).toBeDisabled();const tick=await page.getByTestId('duel').getAttribute('data-tick');await page.waitForTimeout(600);await expect(page.getByTestId('duel')).toHaveAttribute('data-tick',tick!);await page.getByTitle('Réinitialiser le duel').click();await expect(page.getByLabel('Stratégie équipe A')).toBeEnabled();await expect(page.getByTestId('duel')).toHaveAttribute('data-tick','0');await page.getByRole('button',{name:'Retour à mon entrepôt',exact:true}).click();await page.getByRole('button',{name:'Sauvegarder',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('swarm-save'))).toBe(saved);expect(errors).toEqual([]);
});
test('identical Priority First teams finish with real equal statistics and exact replay',async({page})=>{
 test.setTimeout(70000);await open(page);await page.getByLabel('Conditions initiales').selectOption('urgent');await page.getByLabel('Nombre de commandes').fill('25');await page.getByLabel('Durée du duel').selectOption('120');await page.getByLabel('Stratégie équipe A').selectOption('priority');await page.getByLabel('Stratégie équipe B').selectOption('priority');await page.getByRole('button',{name:'×10',exact:true}).click();await page.getByRole('button',{name:'Lancer le duel',exact:true}).click();await expect(page.getByTestId('duel')).toHaveAttribute('data-status','finished',{timeout:30000});await expect(page.locator('.winner')).toContainText('Égalité');const rows=page.getByTestId('duel-report').locator('tbody tr');for(const row of await rows.all()){const cells=row.locator('td');expect(await cells.nth(0).innerText()).toBe(await cells.nth(1).innerText());}const report=await page.getByTestId('duel-report').locator('tbody').innerText();await expect(page.getByTestId('duel-report')).toContainText('Commandes urgentes livrées');await page.setViewportSize({width:1920,height:1080});await page.getByText('Répartition des missions par robot',{exact:true}).click();await page.screenshot({path:'artifacts/swarm-arena-advanced-report.png',fullPage:true});await page.getByRole('button',{name:'Rejouer exactement le même duel',exact:true}).click();await expect(page.getByTestId('duel')).toHaveAttribute('data-status','finished',{timeout:30000});expect(await page.getByTestId('duel-report').locator('tbody').innerText()).toBe(report);
});
test('Eco Drive versus Sprint shows both maps, live metrics and responsive selectors',async({page})=>{
 test.setTimeout(45000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await open(page);await page.getByLabel('Conditions initiales').selectOption('energy');await page.getByLabel('Nombre de commandes').fill('50');await page.getByLabel('Durée du duel').selectOption('120');await page.getByLabel('Stratégie équipe A').selectOption('nearest');await page.getByLabel('Stratégie équipe B').selectOption('eco');for(const width of [1440,1280,390]){await page.setViewportSize({width,height:width===390?844:1000});await expect(page.getByRole('img',{name:'Entrepôt interactif'})).toHaveCount(2);for(const side of ['nearest','balanced'])await expect(page.getByTestId('arena-'+side).getByRole('img',{name:'Entrepôt interactif'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width+1);await page.screenshot({path:`artifacts/swarm-arena-advanced-${width}.png`,fullPage:true});}await page.setViewportSize({width:1440,height:1000});await page.getByRole('button',{name:'×10',exact:true}).click();await page.getByRole('button',{name:'Lancer le duel',exact:true}).click();await expect(page.getByTestId('duel')).toHaveAttribute('data-status','finished',{timeout:30000});await expect(page.getByTestId('arena-balanced')).toHaveAttribute('data-strategy','eco');await expect(page.getByTestId('duel-report')).toContainText('ECO DRIVE');await expect(page.getByTestId('duel-report')).toContainText('Énergie totale');expect(errors).toEqual([]);
});
