import {Engine} from '../src/engine';
import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{await page.addInitScript(snapshot=>{if(!localStorage.getItem('swarm-save'))localStorage.setItem('swarm-save',snapshot)},new Engine(42,{demo:true}).serialize())});

test('presentation 1 creates a product, stocks A-1 and delivers five real units with R001',async({page})=>{
 test.setTimeout(65000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await page.getByTitle('Reprendre (Espace)').click();await page.getByTitle('Mettre en pause (Espace)').click();await page.getByRole('button',{name:'Stocks & Commandes',exact:true}).click();
 await page.getByRole('tab',{name:'Produits'}).click();await page.getByLabel('Nom du produit').fill('Coca-Cola');await page.getByLabel('Référence SKU').fill('COCA');await page.getByLabel('Valeur unitaire').fill('12');await page.getByRole('button',{name:'Créer le produit',exact:true}).click();
 await page.getByRole('tab',{name:'Liste',exact:true}).click();await page.getByRole('button',{name:'Gérer A-1',exact:true}).click();
 await page.getByLabel('Quantité à ajouter ou retirer',{exact:true}).fill('12');page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Retirer les marchandises',exact:true}).click();
 await page.getByLabel('Produit de l’emplacement').selectOption('COCA');await page.getByRole('button',{name:'Enregistrer les modifications',exact:true}).click();await page.getByLabel('Quantité à ajouter ou retirer',{exact:true}).fill('10');await page.getByRole('button',{name:/Ajouter les marchandises/}).click();await page.getByLabel('Robot prioritaire',{exact:true}).selectOption({label:'R001'});await page.getByRole('button',{name:'Enregistrer les modifications',exact:true}).click();
 await page.setViewportSize({width:1920,height:1080});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'artifacts/swarm-inventory.png',fullPage:true});
 await page.getByRole('button',{name:'Commander depuis cet emplacement',exact:true}).click();await page.getByLabel('Quantité',{exact:true}).fill('5');await page.getByLabel('Robot affecté',{exact:true}).selectOption((await page.getByLabel('Robot affecté',{exact:true}).locator('option').filter({hasText:'R001'}).getAttribute('value'))!);
 await page.getByRole('button',{name:'Créer la commande',exact:true}).click();await page.getByRole('button',{name:'Sauvegarder',exact:true}).click();const initial=await page.evaluate(()=>JSON.parse(localStorage.getItem('swarm-save')!));const order=initial.orders.at(-1);expect(order.sku).toBe('COCA');expect(order.quantity).toBe(5);expect(order.sourceId).toBe(initial.tiles.find((t:{location:string})=>t.location==='A-1').id);
 await page.getByRole('button',{name:'Simulation',exact:true}).click();await page.getByRole('button',{name:'×10',exact:true}).click();await page.getByTitle('Reprendre (Espace)').click();
 await expect.poll(async()=>{await page.getByRole('button',{name:'Sauvegarder',exact:true}).click();return page.evaluate(id=>JSON.parse(localStorage.getItem('swarm-save')!).orders.find((o:{id:string})=>o.id===id).status,order.id)}, {timeout:40000,intervals:[1500]}).toBe('completed');
 await page.getByTitle('Mettre en pause (Espace)').click();const final=await page.evaluate(()=>JSON.parse(localStorage.getItem('swarm-save')!));expect(final.tiles.find((t:{location:string})=>t.location==='A-1').stock).toBe(5);expect(final.orders.find((o:{id:string})=>o.id===order.id).income).toBe(60);expect(errors).toEqual([]);
});
test('presentation 2 laboratory fault, paid repair, restoration and guided fusion',async({page})=>{
 await page.goto('/');await page.getByTitle('Reprendre (Espace)').click();await page.getByTitle('Mettre en pause (Espace)').click();await page.getByRole('button',{name:'Sauvegarder',exact:true}).click();const original=await page.evaluate(()=>localStorage.getItem('swarm-save'));
 await page.getByRole('button',{name:'SWARM LAB',exact:true}).click();await page.getByRole('button',{name:'Déclencher l’incident',exact:true}).click();await expect(page.locator('.diagnostic-card')).toContainText('En panne');
 await page.getByRole('button',{name:/Réparer ·/}).first().click();await page.getByRole('button',{name:'Sauvegarder',exact:true}).click();const repaired=await page.evaluate(()=>JSON.parse(localStorage.getItem('swarm-save')!));expect(repaired.robots.some((r:{state:string})=>r.state==='fault')).toBe(false);expect(repaired.budget).toBe(JSON.parse(original!).budget-90);
 await page.setViewportSize({width:1920,height:1080});await page.screenshot({path:'artifacts/swarm-lab.png',fullPage:true});page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Restaurer l’état initial du Lab',exact:true}).click();await page.getByRole('button',{name:'Sauvegarder',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('swarm-save'))).toBe(original);
 await page.getByRole('button',{name:'Visite guidée · Démo intelligente',exact:true}).click();await expect(page.getByRole('button',{name:/Voir les livraisons/})).toBeVisible();await page.getByRole('button',{name:'Retour à ma partie conservée',exact:true}).click();await page.getByRole('button',{name:'Sauvegarder',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('swarm-save'))).toBe(original);
});
test('presentation 3 arena 50 orders two minutes, equal cameras and repeatable results',async({page})=>{
 test.setTimeout(65000);await page.goto('/');await page.getByTitle('Reprendre (Espace)').click();await page.getByTitle('Mettre en pause (Espace)').click();await page.getByRole('button',{name:'SWARM ARENA',exact:true}).click();await page.getByLabel('Conditions initiales').selectOption('2026');await page.getByLabel('Nombre de commandes').fill('50');await page.getByLabel('Durée du duel').selectOption('240');await page.getByRole('button',{name:'×10',exact:true}).click();
 await page.getByTestId('arena-nearest').getByTitle('Agrandir',{exact:true}).click();expect(await page.getByTestId('arena-nearest').locator('.map-controls').innerText()).toBe(await page.getByTestId('arena-balanced').locator('.map-controls').innerText());
 await page.getByRole('button',{name:'Lancer le duel',exact:true}).click();await expect(page.getByTestId('duel')).toHaveAttribute('data-status','finished',{timeout:25000});const report=await page.getByTestId('duel-report').locator('tbody').innerText();expect(await page.getByTestId('duel-report').innerText()).toContain('SMART BALANCE');await page.setViewportSize({width:1920,height:1080});await page.screenshot({path:'artifacts/swarm-arena-50.png',fullPage:true});
 await page.getByRole('button',{name:'Rejouer exactement le même duel',exact:true}).click();await expect(page.getByTestId('duel')).toHaveAttribute('data-status','finished',{timeout:25000});expect(await page.getByTestId('duel-report').locator('tbody').innerText()).toBe(report);
});
test('Copilot requires confirmation, handles ambiguity and uses true catalogue',async({page})=>{
 await page.goto('/');await page.getByTitle('Reprendre (Espace)').click();await page.getByTitle('Mettre en pause (Espace)').click();await page.getByRole('button',{name:'SWARM Copilot',exact:true}).click();await page.getByLabel('Instruction en français').fill('Crée un produit Fanta.');await page.getByRole('button',{name:'Analyser',exact:true}).click();await expect(page.getByRole('button',{name:'Confirmer l’opération',exact:true})).toBeVisible();await page.getByRole('button',{name:'Sauvegarder',exact:true}).click();expect((await page.evaluate(()=>JSON.parse(localStorage.getItem('swarm-save')!))).products.some((p:{name:string})=>p.name==='fanta')).toBe(false);
 await page.getByRole('button',{name:'Confirmer l’opération',exact:true}).click();await page.getByLabel('Instruction en français').fill('mets quelque chose quelque part');await page.getByRole('button',{name:'Analyser',exact:true}).click();await expect(page.locator('.copilot-messages')).toContainText('ambiguë');await page.getByRole('button',{name:'Sauvegarder',exact:true}).click();expect((await page.evaluate(()=>JSON.parse(localStorage.getItem('swarm-save')!))).products.some((p:{sku:string})=>p.sku==='FANTA')).toBe(true);
});
test('management tables and fleet remain usable on mobile without page overflow',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width:390,height:844});await page.goto('/');await page.getByTitle('Reprendre (Espace)').click();for(const section of ['Stocks & Commandes','Flotte de robots','Stations de recharge','SWARM LAB','Analytics','Événements']){await page.getByRole('button',{name:section,exact:true}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(391);}await page.getByRole('button',{name:'Flotte de robots',exact:true}).click();await page.screenshot({path:'artifacts/swarm-fleet-mobile.png',fullPage:true});await page.setViewportSize({width:1920,height:1080});await page.screenshot({path:'artifacts/swarm-fleet.png',fullPage:true});expect(errors).toEqual([]);
});
test('shelf card opens a source-specific order and Lab restores after an editor visit',async({page})=>{
 await page.goto('/');await page.getByTitle('Reprendre (Espace)').click();await page.getByTitle('Mettre en pause (Espace)').click();await page.getByRole('button',{name:'Sauvegarder',exact:true}).click();const original=await page.evaluate(()=>localStorage.getItem('swarm-save'));const shelf=JSON.parse(original!).tiles.find((t:{kind:string})=>t.kind==='shelf');
 await page.locator('g.tile-shelf').first().click();await page.getByRole('button',{name:'Commander depuis cet emplacement',exact:true}).click();await expect(page.getByRole('tab',{name:'Commandes',exact:true})).toHaveAttribute('aria-selected','true');await expect(page.getByLabel('Source du prélèvement',{exact:true})).toHaveValue(shelf.id);
 await page.getByRole('button',{name:'SWARM LAB',exact:true}).click();await page.locator('.incident-cards button').filter({hasText:'Commandes massives'}).click();await page.getByRole('button',{name:'Déclencher l’incident',exact:true}).click();await page.getByText('Outils de comparaison et aménagement',{exact:true}).click();await page.getByRole('button',{name:'Modifier le plan',exact:true}).click();await page.getByRole('button',{name:'SWARM LAB',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('swarm-save'))).toBe(original);page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Restaurer l’état initial du Lab',exact:true}).click();await page.getByRole('button',{name:'Sauvegarder',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('swarm-save'))).toBe(original);
});
