/* eslint-disable @typescript-eslint/no-explicit-any -- Browser assertions inspect serialized legacy and current saves. */
import {test,expect,type Page} from '@playwright/test';
async function snapshot(page:Page){await page.getByRole('button',{name:'Sauvegarder',exact:true}).click();return page.evaluate(()=>JSON.parse(localStorage.getItem('swarm-save')!));}
async function supply(page:Page,quantity:number,manual=false){await page.getByRole('button',{name:'+ Ajouter du stock',exact:true}).click();await page.getByLabel('Produit à approvisionner').selectOption('COCA');await page.getByLabel('Quantité à approvisionner').fill(String(quantity));if(manual){await page.getByLabel('Placement du stock').selectOption('manual');await page.locator('g.tile-shelf').filter({has:page.locator('title').filter({hasText:/^A-1 ·/})}).click();}await page.getByRole('button',{name:'Confirmer l’ajout de stock',exact:true}).click();}
async function coca(page:Page){await page.getByRole('tab',{name:'Produits',exact:true}).click();await page.getByLabel('Nom du produit',{exact:true}).fill('Coca-Cola');await page.getByLabel('Référence SKU').fill('COCA');await page.getByLabel('Valeur unitaire').fill('12');await page.getByRole('button',{name:'Créer le produit',exact:true}).click();}
const stock=(s:any)=>s.tiles.filter((t:any)=>t.sku==='COCA').reduce((n:number,t:any)=>n+t.stock,0);
test('normal game: empty catalogue stock, supply 100 and 50, deliver automatic and manual orders, large supply and save',async({page})=>{
 test.setTimeout(100000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.getByTitle('Mettre en pause (Espace)').click();let s=await snapshot(page);expect(s.orders).toHaveLength(0);expect(s.revenue).toBe(0);expect(s.robots.map((r:any)=>r.battery)).toEqual([95,89,83,77,71,65]);expect(s.robots.every((r:any)=>r.cargo===0)).toBe(true);
 await page.getByRole('button',{name:'Stocks & Commandes',exact:true}).click();await coca(page);expect(stock(await snapshot(page))).toBe(0);await supply(page,100);await supply(page,50,true);s=await snapshot(page);expect(stock(s)).toBe(150);expect(s.orders).toHaveLength(0);expect(s.budget).toBe(11300);
 for(const [quantity,manual] of [[10,false],[5,true]] as const){await page.getByRole('tab',{name:'Commandes',exact:true}).click();await page.getByRole('combobox',{name:'Produit',exact:true}).selectOption('COCA');await page.getByLabel('Quantité',{exact:true}).fill(String(quantity));if(manual)await page.getByLabel('Robot affecté').selectOption(s.robots[0].id);await page.getByRole('button',{name:'Créer la commande',exact:true}).click();const created=(await snapshot(page)).orders.at(-1);await page.getByRole('button',{name:'×10',exact:true}).click();await page.getByRole('button',{name:'Reprendre la simulation',exact:true}).click();await expect.poll(async()=> (await snapshot(page)).orders.find((o:any)=>o.id===created.id).status,{timeout:40000,intervals:[1000]}).toBe('completed');await page.getByRole('button',{name:'Pause de la simulation',exact:true}).click();if(manual)expect((await snapshot(page)).orders.at(-1).assignments.every((a:any)=>a.robotId===s.robots[0].id)).toBe(true);}
 s=await snapshot(page);expect(stock(s)).toBe(135);expect(s.revenue).toBe(180);await page.getByLabel('Sandbox : approvisionnement gratuit').check();const budget=(await snapshot(page)).budget;await supply(page,1000);await supply(page,10000);s=await snapshot(page);expect(stock(s)).toBe(11135);expect(s.budget).toBe(budget);expect(s.subsidizedSupply).toBe(88000);expect(s.orders).toHaveLength(2);expect(s.robots).toHaveLength(6);await expect(page.locator('g.tile-shelf')).toHaveCount(40);await page.screenshot({path:'artifacts/swarm-supply-large-stock.png',fullPage:true});const saved=await snapshot(page);await page.reload();expect(await snapshot(page)).toEqual(saved);expect(errors).toEqual([]);
});
test('visible validation refuses insufficient stock and invalid quantities; shelf settings do not supply stock',async({page})=>{
 await page.goto('/');await page.getByTitle('Mettre en pause (Espace)').click();await page.getByRole('button',{name:'Stocks & Commandes',exact:true}).click();await coca(page);await page.getByRole('tab',{name:'Commandes',exact:true}).click();await page.getByRole('combobox',{name:'Produit',exact:true}).selectOption('COCA');await page.getByLabel('Quantité',{exact:true}).fill('100');await expect(page.locator('#order-validation')).toContainText('Stock insuffisant');await expect(page.getByRole('button',{name:'Créer la commande',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Approvisionner ce produit',exact:true}).click();await expect(page.getByLabel('Quantité à approvisionner')).toHaveValue('100');await page.getByLabel('Quantité à approvisionner').fill('-1');await expect(page.getByRole('button',{name:'Confirmer l’ajout de stock',exact:true})).toBeDisabled();await expect(page.locator('.supply-preview')).toContainText('Quantité');await page.screenshot({path:'artifacts/swarm-supply-validation.png',fullPage:true});await page.getByRole('button',{name:'Annuler l’approvisionnement',exact:true}).click();await supply(page,20);await page.getByRole('button',{name:'Enregistrer les modifications',exact:true}).click();expect(stock(await snapshot(page))).toBe(20);await expect(page.getByLabel('Unités à ajouter à la validation')).toHaveCount(0);await page.getByRole('tab',{name:'Commandes',exact:true}).click();await page.getByRole('combobox',{name:'Produit',exact:true}).selectOption('COCA');await page.getByLabel('Quantité',{exact:true}).fill('100');await expect(page.locator('#order-validation')).toContainText('20 Coca-Cola disponibles');await page.getByLabel('Quantité',{exact:true}).fill('1.5');await expect(page.locator('#order-validation')).toContainText('Quantité invalide');expect((await snapshot(page)).orders).toHaveLength(0);
});
test('new product supply and Copilot use the same large-quantity workflow on mobile',async({page})=>{
 await page.goto('/');await page.getByTitle('Mettre en pause (Espace)').click();await page.getByRole('button',{name:'Stocks & Commandes',exact:true}).click();await page.getByLabel('Sandbox : approvisionnement gratuit').check();await page.getByRole('button',{name:'SWARM Copilot — Stock',exact:true}).click();await page.getByLabel('Instruction en français').fill('Crée Eau et ajoute 1 000 unités dans un rayonnage libre');await page.getByRole('button',{name:'Analyser',exact:true}).click();await page.getByRole('button',{name:'Confirmer l’opération',exact:true}).click();let s=await snapshot(page);expect(s.products.some((p:any)=>p.sku==='EAU')).toBe(true);expect(s.tiles.filter((t:any)=>t.sku==='EAU').reduce((n:number,t:any)=>n+t.stock,0)).toBe(1000);expect(s.orders).toHaveLength(0);await page.getByRole('button',{name:'Fermer Copilot',exact:true}).click();await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'+ Ajouter du stock',exact:true}).click();await page.getByLabel('Produit à approvisionner').selectOption('__new__');await page.getByLabel('Nom du nouveau produit').fill('Fanta');await page.getByLabel('Quantité à approvisionner').fill('10000');expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(391);await page.screenshot({path:'artifacts/swarm-supply-mobile.png',fullPage:true});await page.getByRole('button',{name:'Créer le produit et ajouter du stock',exact:true}).click();s=await snapshot(page);expect(s.tiles.filter((t:any)=>t.sku==='FANTA').reduce((n:number,t:any)=>n+t.stock,0)).toBe(10000);expect(s.orders).toHaveLength(0);
});


