import {test,expect} from '@playwright/test';
import type {Page} from '@playwright/test';
import {createManagementDemo} from '../src/managementDemo';
const initial=createManagementDemo;
async function start(page:Page){const e=initial();await page.addInitScript(snapshot=>{if(!localStorage.getItem('swarm-save'))localStorage.setItem('swarm-save',snapshot)},e.serialize());await page.goto('/');return e;}
const rack=(page:Page,location:string)=>page.locator('g.tile-shelf').filter({has:page.locator('title').filter({hasText:new RegExp('^'+location+' ·')})});
async function state(page:Page){await page.getByRole('button',{name:'Sauvegarder',exact:true}).click();return page.evaluate(()=>JSON.parse(localStorage.getItem('swarm-save')!));}
async function ask(page:Page,text:string,confirm=false){await page.getByLabel('Instruction en français').fill(text);await page.getByRole('button',{name:'Analyser',exact:true}).click();if(confirm)await page.getByRole('button',{name:'Confirmer l’opération',exact:true}).click();}
test('six-step presentation: map stock, automatic stock, location, robot rules, real delivery and paid Lab repair',async({page})=>{
 test.setTimeout(65000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.getByTitle('Mettre en pause (Espace)').click();const original=await state(page);await page.getByRole('button',{name:'Paramètres',exact:true}).click();await page.getByRole('button',{name:'Préparer la démonstration UX',exact:true}).click();const e=initial(),r=e.state.robots[0];await page.setViewportSize({width:1920,height:1080});
 await page.getByRole('button',{name:'Stocks & Commandes',exact:true}).click();await expect(page.getByRole('tab',{name:'Entrepôt',exact:true})).toHaveAttribute('aria-selected','true');await expect(page.locator('.table-scroll')).toHaveCount(0);await rack(page,'A-1').click();await page.getByLabel('Produit de l’emplacement').selectOption('COCA');await page.getByLabel('Unités à ajouter à la validation').fill('10');await page.getByLabel('Robot prioritaire',{exact:true}).selectOption(r.id);await page.getByRole('button',{name:'Enregistrer les modifications',exact:true}).click();await rack(page,'A-1').hover();await expect(page.getByRole('tooltip')).toContainText('Stock total : 10');await expect(page.getByRole('tooltip')).toContainText('Prioritaire : R001');await page.mouse.move(20,20);await page.screenshot({path:'artifacts/swarm-ux-stock-map.png',fullPage:true});
 await page.getByRole('button',{name:'SWARM Copilot — Stock',exact:true}).click();await ask(page,'Ajoute 20 Fanta dans un emplacement libre.',true);await expect(page.locator('.copilot-messages')).toContainText('20 Fanta ajoutés dans A-2');await expect(page.locator('.workspace-context')).toContainText('Emplacement A-2');await ask(page,'Dans quelle case se trouve le Coca-Cola ?');await expect(page.locator('.copilot-messages')).toContainText('A-1 (10 disponibles)');await expect(page.locator('.workspace-context')).toContainText('Emplacement A-1');await page.getByRole('button',{name:'Fermer Copilot',exact:true}).click();
 await page.getByRole('button',{name:'Flotte de robots',exact:true}).click();await page.locator(`g.robot[data-robot-id="${r.id}"]`).click();await page.getByLabel('Mode d’autorisation').selectOption('products');await page.getByLabel('Coca-Cola',{exact:true}).check();await page.getByRole('button',{name:'Enregistrer les autorisations',exact:true}).click();await page.getByRole('button',{name:'SWARM Copilot — Robots',exact:true}).click();await ask(page,'R003 travaille seulement sur A-1 et A-2.',true);await ask(page,'Quels robots peuvent récupérer le Coca-Cola de A-1 ?');await expect(page.locator('.copilot-messages')).toContainText('Robots autorisés');await page.getByRole('button',{name:'Fermer Copilot',exact:true}).click();await page.screenshot({path:'artifacts/swarm-ux-fleet-map.png',fullPage:true});
 await page.getByRole('button',{name:'Stocks & Commandes',exact:true}).click();await page.getByRole('button',{name:'SWARM Copilot — Stock',exact:true}).click();await ask(page,'Crée une commande urgente de 5 Coca-Cola depuis A-1.',true);await page.getByRole('button',{name:'Fermer Copilot',exact:true}).click();const before=await state(page),order=before.orders.at(-1);expect(order.quantity).toBe(5);expect(order.sourceId).toBe(e.state.tiles.find(t=>t.location==='A-1')!.id);await page.getByRole('button',{name:'×10',exact:true}).click();await page.getByRole('button',{name:'Reprendre la simulation',exact:true}).click();await expect.poll(async()=>{const s=await state(page);return s.orders.find((o:{id:string})=>o.id===order.id).status},{timeout:35000,intervals:[1000]}).toBe('completed');await page.getByRole('button',{name:'Pause de la simulation',exact:true}).click();const delivered=await state(page);expect(delivered.tiles.find((t:{location:string})=>t.location==='A-1').stock).toBe(5);expect(delivered.orders.at(-1).income).toBe(60);expect(delivered.orders.at(-1).assignments.some((a:{robotId:string})=>a.robotId===r.id)).toBe(true);
 await page.getByRole('button',{name:'SWARM LAB',exact:true}).click();await page.locator('.incident-cards button').filter({hasText:'Robot en panne'}).click();await page.locator(`g.robot[data-robot-id="${r.id}"]`).click();await expect(page.getByLabel('Robot cible')).toHaveValue(r.id);await page.getByRole('button',{name:'Déclencher l’incident',exact:true}).click();await expect(page.locator('.diagnostic-card')).toContainText('R001 · En panne');const failed=await state(page);expect(failed.robots.find((x:{id:string})=>x.id===r.id).state).toBe('fault');await page.screenshot({path:'artifacts/swarm-ux-lab-incident.png',fullPage:true});await page.getByRole('button',{name:/Réparer ·/}).click();const repaired=await state(page);expect(repaired.budget).toBe(failed.budget-90);await expect(page.locator('.incident-history')).toContainText('Résolu');await page.getByRole('button',{name:'Quitter la démo',exact:true}).click();expect(await state(page)).toEqual(original);expect(errors).toEqual([]);
});
test('map multi-selection can cancel without changes, then persists only confirmed locations',async({page})=>{
 const e=await start(page),r=e.state.robots[2];await page.getByRole('button',{name:'Flotte de robots',exact:true}).click();await page.locator('.compact-fleet button').filter({hasText:'R003'}).click();await page.getByLabel('Mode d’autorisation').selectOption('locations');await page.getByRole('button',{name:'Sélectionner sur la carte',exact:true}).click();await rack(page,'A-1').click();await rack(page,'A-2').click();await expect(page.locator('.selection-banner')).toContainText('2 choisis');await page.getByRole('button',{name:'Annuler la sélection',exact:true}).click();expect((await state(page)).robots.find((x:{id:string})=>x.id===r.id).allowedLocations).toBeUndefined();await page.getByRole('button',{name:'Sélectionner sur la carte',exact:true}).click();await rack(page,'A-1').click();await rack(page,'A-2').click();await page.getByRole('button',{name:'Confirmer la sélection',exact:true}).click();const saved=await state(page),rules=saved.robots.find((x:{id:string})=>x.id===r.id).allowedLocations;expect(rules).toEqual(e.state.tiles.filter(t=>['A-1','A-2'].includes(t.location??'')).map(t=>t.id));await page.reload();await page.getByRole('button',{name:'Flotte de robots',exact:true}).click();await page.locator('.compact-fleet button').filter({hasText:'R003'}).click();await expect(page.getByLabel('Mode d’autorisation')).toHaveValue('locations');expect((await state(page)).robots.find((x:{id:string})=>x.id===r.id).allowedLocations).toEqual(rules);
});
test('Lab exposes relevant parameters only, selects a free cell and keeps separate incident resolutions across navigation',async({page})=>{
 const e=await start(page);await page.getByRole('button',{name:'SWARM LAB',exact:true}).click();await expect(page.getByLabel('Robot cible')).toBeVisible();await expect(page.getByLabel('Nombre de commandes')).toHaveCount(0);await expect(page.getByLabel('Rayonnage cible')).toHaveCount(0);await page.getByRole('button',{name:'Déclencher l’incident',exact:true}).click();await page.locator('.incident-cards button').filter({hasText:'Passage bloqué'}).click();await expect(page.getByLabel('Robot cible')).toHaveCount(0);await page.locator('.floor-hit').first().click();await page.getByRole('button',{name:'Déclencher l’incident',exact:true}).click();await expect(page.locator('.incident-history button')).toHaveCount(2);await expect(page.locator('.lab-resolution')).not.toContainText('Réapprovisionner');await expect(page.locator('.lab-resolution')).not.toContainText('Ajouter une borne');expect((await state(page)).tiles.some((t:{kind:string;x:number;y:number})=>t.kind==='wall'&&t.x===0&&t.y===0)).toBe(true);await page.getByRole('button',{name:/Retirer l’obstacle ·/}).click();await expect(page.locator('.incident-history button').last()).toContainText('Résolu');await expect(page.locator('.incident-history button').first()).toContainText('Actif');await page.getByRole('button',{name:'Stocks & Commandes',exact:true}).click();await page.getByRole('button',{name:'SWARM LAB',exact:true}).click();await expect(page.locator('.incident-history button')).toHaveCount(2);await page.locator('.incident-history button').first().click();await page.getByRole('button',{name:/Réparer ·/}).click();await expect(page.locator('.incident-history button').first()).toContainText('Résolu');page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Restaurer l’état initial du Lab',exact:true}).click();await expect(page.locator('.incident-history button')).toHaveCount(0);expect(JSON.stringify(await state(page))).toBe(e.serialize());
});
test('new map workspaces and Copilot remain readable at laptop and mobile sizes',async({page})=>{
 await start(page);for(const width of [1280,390]){await page.setViewportSize({width,height:width===390?844:900});for(const section of ['Stocks & Commandes','Flotte de robots','SWARM LAB']){await page.getByRole('button',{name:section,exact:true}).click();await expect(page.getByRole('img',{name:'Entrepôt interactif'})).toBeVisible();expect(await page.locator('.workspace-map').evaluate(el=>el.getBoundingClientRect().height)).toBeGreaterThan(300);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width+1);if(section==='Stocks & Commandes'){await rack(page,'A-1').click();await expect(page.locator('.workspace-context')).toContainText('Emplacement A-1');}await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:`artifacts/swarm-ux-${section==='SWARM LAB'?'lab':section==='Flotte de robots'?'fleet':'stock'}-${width}.png`,fullPage:true});}}
 await page.getByRole('button',{name:'Stocks & Commandes',exact:true}).click();await page.getByRole('button',{name:'SWARM Copilot — Stock',exact:true}).click();await expect(page.getByRole('region',{name:'SWARM Copilot — Stock'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(391);
});
test('fleet actions follow real availability, charge repairs once and reactivate administrative suspension',async({page})=>{
 await start(page);await page.getByRole('button',{name:'Flotte de robots',exact:true}).click();await page.locator('.compact-fleet button').filter({hasText:'R001'}).click();const panel=page.locator('.workspace-context');await expect(panel.getByRole('button',{name:'Recharger',exact:true})).toBeVisible();await panel.getByRole('button',{name:'Panne',exact:true}).click();const failed=await state(page);await expect(panel.getByRole('button',{name:'Recharger',exact:true})).toHaveCount(0);await expect(panel.getByRole('button',{name:/Réparer ·/})).toHaveCount(1);await panel.getByRole('button',{name:/Réparer ·/}).click();expect((await state(page)).budget).toBe(failed.budget-90);await expect(panel.getByRole('button',{name:/Réparer ·/})).toHaveCount(0);await panel.getByRole('button',{name:'Mettre hors service',exact:true}).click();await expect(panel.getByRole('button',{name:'Réactiver R001',exact:true})).toBeVisible();await expect(panel.getByRole('button',{name:'Panne',exact:true})).toHaveCount(0);await expect(panel.getByRole('button',{name:/Réparer ·/})).toHaveCount(0);await panel.getByRole('button',{name:'Réactiver R001',exact:true}).click();await expect(panel.getByRole('button',{name:'Panne',exact:true})).toBeVisible();expect((await state(page)).budget).toBe(failed.budget-90);
});
