import {describe,it,expect} from 'vitest';
import {Engine} from './engine';
import {DuelSession,criterionWinner} from './duel';
import {STRATEGIES,STRATEGY_IDS,type MissionEstimate} from './arenaStrategies';
import {prepareArena} from './arena';
function fixture(){const e=new Engine();const shelf=e.state.tiles.find(t=>t.location==='A-1')!;shelf.sku='A';shelf.stock=100;e.state.robots.forEach((r,i)=>{r.disabled=i>1;r.battery=95;});Object.assign(e.state.robots[0],{x:4,y:3});Object.assign(e.state.robots[1],{x:9,y:3});return e;}
const estimate:MissionEstimate={pickup:3,delivery:12,energy:2.52,returnEnergy:2,chargerAvailable:true,hasCharger:true,battery:80,assignments:0,workSeconds:0,distance:0};
describe('Arena coordination strategies',()=>{
 it.each(STRATEGY_IDS)('%s is selectable, independent, deterministic and resettable',id=>{const prepared=prepareArena(new Engine().serialize(),'batteries',10),d=new DuelSession(prepared.snapshot,30,id,id);expect(d.nearest.state.strategy).toBe(id);const a=JSON.parse(d.nearest.serialize()),b=JSON.parse(d.balanced.serialize());expect(a).toEqual(b);expect(d.nearest.state.tiles[0]).not.toBe(d.balanced.state.tiles[0]);d.tick(30);expect(d.nearest.serialize()).toBe(d.balanced.serialize());expect(d.winner).toBe('tie');const first=d.nearest.serialize();d.reset();expect(d.elapsed).toBe(0);d.tick(30);expect(d.nearest.serialize()).toBe(first);expect(()=>Engine.restore(first)).not.toThrow();});
 it('uses distinct formulas with whole-trip energy, charger safety and accumulated work',()=>{expect(STRATEGIES.nearest.score(estimate)).toBe(3);expect(STRATEGIES.balanced.score(estimate)).toBe(5.4);expect(STRATEGIES.eco.score(estimate)).toBe(2.52);expect(STRATEGIES.guardian.score({...estimate,chargerAvailable:false})).toBeGreaterThan(STRATEGIES.guardian.score(estimate));expect(STRATEGIES.guardian.admissible({...estimate,returnEnergy:70})).toBe(false);expect(STRATEGIES.guardian.admissible({...estimate,hasCharger:false})).toBe(false);expect(STRATEGIES.fairness.score({...estimate,assignments:2,workSeconds:50,distance:40})).toBe(212);});
 it('Priority First actually overtakes older low-priority orders with constrained robots',()=>{const e=fixture();e.state.robots[1].disabled=true;e.createOrder('A',1,1);e.createOrder('A',1,3);e.createOrder('A',1,3);const d=new DuelSession(e.serialize(),20,'nearest','priority');d.tick();expect(d.nearest.state.robots[0].orderId).toBe(e.state.orders[0].id);expect(d.balanced.state.robots[0].orderId).toBe(e.state.orders[1].id);});
 it('Eco Drive selects a less costly real stock-to-depot trip rather than nearest pickup',()=>{const e=fixture();e.state.robots[1].disabled=true;const s=e.state.tiles.filter(t=>t.kind==='shelf');s.forEach(t=>{t.stock=0;});const near=s.find(t=>t.x===5&&t.y===3)!,far=s.find(t=>t.x===17&&t.y===3)!;near.stock=20;near.sku='A';far.stock=20;far.sku='A';e.createOrder('A',1);const d=new DuelSession(e.serialize(),20,'nearest','eco');d.tick();expect(d.nearest.state.robots[0].shelfId).toBe(near.id);expect(d.balanced.state.robots[0].shelfId).toBe(far.id);});
 it('Battery Guardian considers return distance and sends an unsafe available robot to recharge',()=>{const e=fixture();e.state.robots[1].disabled=true;e.state.robots[0].battery=26;Object.assign(e.state.robots[0],{x:0,y:15});const depot=e.state.tiles.find(t=>t.kind==='depot')!,charger=e.state.tiles.find(t=>t.kind==='charger')!;Object.assign(depot,{x:23,y:15});Object.assign(charger,{x:0,y:0});e.state.tiles=e.state.tiles.filter(t=>!['depot','charger'].includes(t.kind)||t.id===depot.id||t.id===charger.id);e.createOrder('A',1);const d=new DuelSession(e.serialize(),20,'nearest','guardian');d.tick();expect(d.nearest.state.robots[0].orderId).toBeTruthy();expect(d.balanced.state.robots[0].orderId).toBeUndefined();expect(['to-charge','charging']).toContain(d.balanced.state.robots[0].state);});
 it('Fleet Fairness chooses a less-used robot even when it is farther away',()=>{const e=fixture();e.createOrder('A',1);const d=new DuelSession(e.serialize(),20,'nearest','fairness');d.balanced.arenaWork.get(e.state.robots[0].id)!.assignments=4;d.tick();expect(d.nearest.state.robots[0].orderId).toBeTruthy();expect(d.balanced.state.robots[1].orderId).toBeTruthy();});
 it.each(STRATEGY_IDS)('%s respects authorization, inventory conservation and unique delivery',id=>{const e=fixture();e.state.robots[0].allowedProducts=['B'];e.createOrder('A',3);const d=new DuelSession(e.serialize(),240,id,id);const initial=e.state.tiles.reduce((n,t)=>n+(t.stock??0),0);for(let i=0;i<240;i++){d.tick();const s=d.nearest.state;expect(new Set(s.robots.map(r=>`${r.x},${r.y}`)).size).toBe(s.robots.length);expect(s.robots.every(r=>r.battery>=0&&r.battery<=100)).toBe(true);expect(s.robots[0].orderId).toBeUndefined();expect(s.tiles.every(t=>(t.stock??0)>=0)).toBe(true);expect(s.robots.every(r=>!s.tiles.some(t=>['shelf','wall'].includes(t.kind)&&t.x===r.x&&t.y===r.y))).toBe(true);expect(s.tiles.reduce((n,t)=>n+(t.stock??0),0)+s.robots.reduce((n,r)=>n+r.cargo,0)+s.orders.reduce((n,o)=>n+o.delivered,0)).toBe(initial);}expect(d.nearest.state.orders[0].delivered).toBe(3);expect(d.nearest.state.revenue).toBe(255);expect(d.metrics('nearest').deliveredUnits).toBe(3);expect(d.metrics('nearest').distribution.reduce((n,r)=>n+r.deliveries,0)).toBe(3);});
 it('handles no fleet, no stock, fault and critical batteries without invented results',()=>{for(const kind of ['fleet','stock','fault','battery','depot']){const e=fixture();e.createOrder('A',1);if(kind==='fleet')e.state.robots=[];if(kind==='stock')e.state.tiles.forEach(t=>{if(t.kind==='shelf')t.stock=0});if(kind==='fault')e.state.robots.forEach(r=>e.faultRobot(r.id));if(kind==='battery')e.state.robots.forEach(r=>e.setBattery(r.id,0));if(kind==='depot')e.state.tiles=e.state.tiles.filter(t=>t.kind!=='depot');const d=new DuelSession(e.serialize(),20,'eco','guardian');d.tick(20);expect(d.metrics('nearest').completed).toBe(0);expect(d.metrics('balanced').completed).toBe(0);expect(d.winner).toBe('tie');expect(d.nearest.state.orders[0].status).not.toBe('completed');}});
 it.each(['batteries','urgent','energy','fleet'])('preset %s is reproducible and never alters the main game',scenario=>{const e=new Engine();const original=e.serialize(),p=prepareArena(original,scenario,50);expect(p).toEqual(prepareArena(original,scenario,50));expect(e.serialize()).toBe(original);const d=new DuelSession(p.snapshot,20,'eco','fairness');const a=JSON.parse(d.nearest.serialize()),b=JSON.parse(d.balanced.serialize());delete a.strategy;delete b.strategy;expect(a).toEqual(b);expect(d.metrics('nearest').total).toBe(50);});
 it('Fleet Fairness improves actual delivery equity with spaced arrivals and asymmetric travel',()=>{const e=fixture();Object.assign(e.state.robots[1],{x:20,y:14});const depot=e.state.tiles.find(t=>t.kind==='depot')!;Object.assign(depot,{x:4,y:3});e.state.tiles=e.state.tiles.filter(t=>t.kind!=='depot'||t.id===depot.id);for(let i=0;i<12;i++){e.createOrder('A',1);e.state.orders.at(-1)!.createdAt=i*30;}const d=new DuelSession(e.serialize(),600,'nearest','fairness');d.tick(600);expect(d.metrics('balanced').fairness).toBeGreaterThan(d.metrics('nearest').fairness);expect(d.metrics('balanced').completed).toBe(12);expect(d.metrics('nearest').completed).toBe(12);});
 it('Arena preparation excludes historical waiting from a copied live game',()=>{const e=fixture();e.createOrder('A',1);e.state.tick=1000;const d=new DuelSession(e.serialize(),120,'nearest','nearest');d.tick(120);expect(d.metrics('nearest').completed).toBe(1);expect(d.metrics('nearest').averageTime).toBeLessThanOrEqual(60);});
 it('live statistics distinguish queued, active and blocked work',()=>{const e=fixture();for(let i=0;i<10;i++)e.createOrder('A',1);const d=new DuelSession(e.serialize(),20,'eco','fairness');d.tick();const m=d.metrics('nearest');expect(m.queued).toBe(d.nearest.state.orders.filter(o=>o.status==='pending').length);expect(m.pending).toBe(10);expect(m.busy).toBe(2);expect(m.impossible).toBe(d.nearest.state.orders.filter(o=>o.status==='blocked').length);});
 it('ranking and criterion ties use actual measured values',()=>{expect(criterionWinner(4,3)).toBe('nearest');expect(criterionWinner(4,3,true)).toBe('balanced');expect(criterionWinner(4,4)).toBe('tie');const d=new DuelSession(fixture().serialize(),20,'eco','fairness');expect(d.winner).toBe('tie');expect(d.metrics('nearest').fairness).toBe(0);expect(()=>new DuelSession('{}',20,'eco','fairness')).toThrow();expect(()=>prepareArena(fixture().serialize(),'unknown',10)).toThrow();});
});
