import {Engine,PRICES} from './engine';
import type {OrderOptions} from './engine';
import type {CopilotPlan} from './copilot';
import {compatibleShelf,stockOperation,transaction} from './operations';
const fold=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[«»".!?]/g,'').replace(/\s+/g,' ').trim();
const skuFor=(name:string)=>fold(name).toUpperCase().replace(/[^A-Z0-9]+/g,'_').slice(0,24);
export function contextualIntent(e:Engine,input:string):CopilotPlan|undefined{
 const raw=fold(input),text=raw.replace(/^ajoute(?:-moi| moi)? (?:un stock de )?/,'ajoute ').replace(/^montre(?:-moi| moi) /,'montre ');
 const info=(message:string,targetIds:string[]=[]):CopilotPlan=>({message,mutates:false,kind:'information',targetIds});
 const fail=(message:string):CopilotPlan=>({message,mutates:false,kind:'impossible'});
 const action=(message:string,execute:NonNullable<CopilotPlan['execute']>,targetIds:string[]=[]):CopilotPlan=>({message,mutates:true,kind:'confirmation',execute,targetIds});
 const product=(name:string)=>e.products.find(p=>fold(p.name)===fold(name)||fold(p.sku)===fold(name));
 const shelf=(code:string)=>e.state.tiles.find(t=>t.kind==='shelf'&&fold(t.location??t.id)===fold(code));
 const robot=(code:string)=>{const codeMatch=fold(code).replace(/^(?:le )?robot (\d+)$/,(_,n)=>`r${n.padStart(3,'0')}`);return e.state.robots.find(r=>fold(r.code??r.id)===codeMatch||fold(r.id)===codeMatch);};
 let m=text.match(/^cree (?:un produit )?(.+?) et ajoute (\d+) unites dans ([a-z]+-\d+)$/);
 let stock=m?{name:m[1],quantity:Number(m[2]),source:m[3],empty:false}:undefined;
 if(!stock){m=text.match(/^(?:ajoute|mets) (\d+) (.+?)(?: dans (un emplacement libre|[a-z]+-\d+))?$/);if(m)stock={name:m[2],quantity:Number(m[1]),source:m[3],empty:m[3]==='un emplacement libre'};}
 if(stock){const p=product(stock.name),sku=p?.sku??skuFor(stock.name),t=stock.source&&!stock.empty?shelf(stock.source):compatibleShelf(e,sku,stock.quantity,stock.empty);if(!t)return fail('Aucun emplacement compatible avec assez de capacité. Libérez un emplacement ou construisez un rayonnage.');if(t.sku!==sku&&((t.stock??0)>0||e.stockInfo(t).reserved))return fail(`${t.location} contient déjà un autre produit. Retirez explicitement son stock disponible avant de le changer.`);
 const probe=transactionPreview(e,copy=>stockOperation(copy,sku,p?.name??stock!.name,stock!.quantity,t.id));if(!probe.ok)return fail(probe.message);
 return action(`${p?'':`Créer ${stock.name} (SKU ${sku}, valeur 85 €, encombrement 1), puis `}ajouter ${stock.quantity} ${p?.name??stock.name} dans ${t.location}, coût ${stock.quantity*PRICES.stockUnit} €. Règle : même produit avec de la place, puis premier emplacement vide par référence.`,()=>stockOperation(e,sku,p?.name??stock!.name,stock!.quantity,t.id),[t.id]);}
 m=text.match(/^(?:dans quelle case se trouve|ou se trouve|ou est) (?:le |la |les |du )?(.+)$/);if(m){const p=product(m[1]);if(!p)return fail('Quel produit recherchez-vous ? Utilisez son nom exact ou son SKU.');const tiles=e.state.tiles.filter(t=>t.kind==='shelf'&&t.sku===p.sku&&(t.stock??0)>0);return info(tiles.length?`${p.name} : ${tiles.map(t=>`${t.location} (${e.stockInfo(t).available} disponibles)`).join(', ')}.`:'Aucune marchandise de ce produit sur les rayonnages.',tiles.map(t=>t.id));}
 if(text==='montre les rayonnages presque vides'||text==='montre les emplacements presque vides'){const tiles=e.state.tiles.filter(t=>t.kind==='shelf'&&e.stockInfo(t).available<5);return info(tiles.length?tiles.map(t=>`${t.location} : ${e.stockInfo(t).available} disponibles`).join(' · '):'Aucun rayonnage avec moins de 5 unités disponibles.',tiles.map(t=>t.id));}
 if(text==='quels robots sont disponibles'){const robots=e.state.robots.filter(r=>r.state==='idle'&&!r.disabled&&r.battery>25);return info(robots.length?robots.map(r=>`${r.code} (${r.battery.toFixed(0)} %)`).join(', '):'Aucun robot immédiatement disponible.',robots.map(r=>r.id));}
 m=text.match(/^quels? robots? (?:peut|peuvent) recuperer (?:du |le |la )?(.+?)(?: de ([a-z]+-\d+))?$/);if(m){const p=product(m[1]),t=m[2]?shelf(m[2]):undefined;if(!p||m[2]&&!t)return fail('Produit ou emplacement inconnu.');const robots=e.state.robots.filter(r=>!r.disabled&&e.state.tiles.some(s=>s.kind==='shelf'&&s.sku===p.sku&&(!t||s.id===t.id)&&e.isAuthorized(r,s)));return info(robots.length?`Robots autorisés : ${robots.map(r=>`${r.code} (${r.state==='idle'?'disponible':r.state==='fault'?'en panne':'occupé ou en recharge'})`).join(', ')}. Stock, autonomie et trajet vérifiés à l’affectation.`:'Aucun robot autorisé par cette combinaison de règles.',robots.map(r=>r.id));}
 const robotPrefix='((?:le )?robot \\d+|r\\d+)';
 m=text.match(new RegExp('^'+robotPrefix+' (?:peut (?:chercher|recuperer) |travaille |est autorise a recuperer )?(?:uniquement|seulement)(?: sur| du| le| la)? (.+)$'));
 if(m){const r=robot(m[1]);if(!r)return fail('Quel robot ? Utilisez R001 ou « robot 1 ».');const names=m[2].split(/ et |,/).map(s=>s.trim()).filter(Boolean),locations=names.map(shelf);if(locations.every(Boolean)){const ids=locations.map(t=>t!.id);return action(`${r.code} pourra prélever uniquement dans ${locations.map(t=>t!.location).join(', ')}.`,()=>transaction(e,copy=>{let result=copy.setRobotProductPermissions(r.id);if(result.ok)result=copy.setRobotPermissions(r.id,ids,(r.priorityLocations??[]).filter(id=>ids.includes(id)));return result;}),[r.id,...ids]);}
 const products=names.map(product);if(products.some(p=>!p))return fail('Quels produits ou rayonnages ? Utilisez leurs noms exacts, séparés par « et ». Aucune mission n’est créée.');return action(`${r.code} sera limité à ${products.map(p=>p!.name).join(', ')}. Aucune commande n’est créée.`,()=>transaction(e,copy=>{let result=copy.setRobotPermissions(r.id,undefined,r.priorityLocations??[]);if(result.ok)result=copy.setRobotProductPermissions(r.id,products.map(p=>p!.sku));return result;}),[r.id]);}
 m=text.match(new RegExp('^'+robotPrefix+' (?:peut recuperer |peut chercher )?(?:tous les produits|tous les stocks)$'));if(m){const r=robot(m[1]);if(!r)return fail('Robot inconnu.');return action(`${r.code} pourra récupérer tous les produits, sous réserve des permissions des rayonnages.`,()=>transaction(e,copy=>{let result=copy.setRobotProductPermissions(r.id);if(result.ok)result=copy.setRobotPermissions(r.id,undefined,r.priorityLocations??[]);return result;}),[r.id]);}
 m=text.match(/^(autorise|interdis) (r\d+) sur ([a-z]+-\d+)$/);if(m){const r=robot(m[2]),t=shelf(m[3]);if(!r||!t)return fail('Robot ou rayonnage inconnu.');const allowed=new Set(r.allowedLocations??e.state.tiles.filter(t=>t.kind==='shelf').map(t=>t.id));if(m[1]==='autorise')allowed.add(t.id);else allowed.delete(t.id);return action(`${m[1]==='autorise'?'Autoriser':'Interdire'} ${r.code} sur ${t.location}, en conservant ses autres restrictions.`,()=>e.setRobotPermissions(r.id,[...allowed],(r.priorityLocations??[]).filter(id=>allowed.has(id))),[r.id,t.id]);}
 m=text.match(/^envoie (.+?) (?:se recharger|en recharge)$/);if(m){const r=robot(m[1]);if(!r)return fail('Robot inconnu.');return action(`Demander une recharge pour ${r.code}. Un colis à bord doit d’abord être livré.`,()=>e.chargeRobot(r.id),[r.id]);}
 m=text.match(/^mets (.+?) hors service$/);if(m){const r=robot(m[1]);if(!r)return fail('Robot inconnu.');return action(`Mettre ${r.code} hors service, avec conservation d’un éventuel colis.`,()=>e.setService(r.id,true),[r.id]);}
 m=text.match(/^envoie (.+?) chercher (\d+) (.+)$/);if(m){const r=robot(m[1]),p=product(m[3]);if(!r||!p)return fail('Précisez le robot, la quantité et le nom exact du produit.');return mission(e,p.sku,Number(m[2]),2,{robotId:r.id},[r.id]);}
 m=text.match(/^cree une commande(?: (urgente|normale|basse))? de (\d+) (.+?) depuis ([a-z]+-\d+)(?: avec (r\d+))?$/);if(m){const p=product(m[3]),t=shelf(m[4]),r=m[5]?robot(m[5]):undefined;if(!p||!t||m[5]&&!r)return fail('Produit, source ou robot inconnu.');return mission(e,p.sku,Number(m[2]),m[1]==='urgente'?3:m[1]==='basse'?1:2,{sourceId:t.id,robotId:r?.id},[t.id,...(r?[r.id]:[])]);}
 m=text.match(/^cree une commande(?: (urgente|normale|basse))? de (\d+) (.+?)(?: avec (r\d+))?$/);if(m){const p=product(m[3]),r=m[4]?robot(m[4]):undefined;if(!p||m[4]&&!r)return fail('Produit ou robot inconnu.');return mission(e,p.sku,Number(m[2]),m[1]==='urgente'?3:m[1]==='basse'?1:2,{robotId:r?.id},r?[r.id]:[]);}
 if(text.startsWith('envoie ')||/\bpeut recuperer\b/.test(text))return fail('Voulez-vous modifier ses autorisations ou créer une commande ? Précisez « uniquement… » ou « chercher 5… ». Aucune mission créée.');
 return undefined;
}
function transactionPreview(e:Engine,operation:(copy:Engine)=>{ok:boolean;message:string}){return operation(Engine.restore(e.serialize()));}
function mission(e:Engine,sku:string,quantity:number,priority:number,options:OrderOptions,targetIds:string[]):CopilotPlan{
 const eligible=e.missionReadyRobots(sku,options);const preview=transactionPreview(e,copy=>copy.createOrder(sku,quantity,priority,options));
 if(!preview.ok||!eligible.length)return {mutates:false,kind:'impossible',message:preview.ok?'Aucun robot autorisé avec assez de batterie et un trajet accessible jusqu’au produit et au dépôt.':preview.message};
 return {mutates:true,kind:'confirmation',message:`Créer une vraie commande de ${quantity} ${e.products.find(p=>p.sku===sku)?.name}${options.sourceId?` depuis ${e.state.tiles.find(t=>t.id===options.sourceId)?.location}`:''}${options.robotId?` avec ${e.state.robots.find(r=>r.id===options.robotId)?.code}`:''}.`,targetIds,execute:()=>e.createOrder(sku,quantity,priority,options)};
}
