import { useState } from 'react';
import { parseCopilot } from './copilot';
import type { Engine, Result } from './engine';
export default function Copilot({engine,report,context='general',focus}:{engine:Engine;report:(r:Result)=>void;context?:'stock'|'robots'|'general';focus?:(ids:string[])=>void}){
 const [open,setOpen]=useState(false),[input,setInput]=useState(''),[pending,setPending]=useState(''),[messages,setMessages]=useState<string[]>([]);
 const title=context==='stock'?'SWARM Copilot — Stock':context==='robots'?'SWARM Copilot — Robots':'SWARM Copilot';
 const send=()=>{const plan=parseCopilot(engine,input);setMessages(m=>[...m.slice(-18),`Vous : ${input}`,`${plan.mutates?'Confirmation demandée':plan.kind==='impossible'?'Action impossible':'Information'} : ${plan.message}`]);setPending(plan.mutates?input:'');if(!plan.mutates&&plan.targetIds?.length)focus?.(plan.targetIds);setInput('')};
 return <div className="copilot-root"><button className="copilot-toggle" onClick={()=>setOpen(!open)}>{title}</button>{open&&<section className="copilot-panel" aria-label={title}><div className="panel-title"><h2>{title}</h2><button aria-label="Fermer Copilot" onClick={()=>setOpen(false)}>×</button></div><p className="hint">Assistant local à intentions prédéfinies. Aucun service externe ni IA générative.</p><div className="copilot-messages" aria-live="polite">{messages.map((m,i)=><p key={i}>{m}</p>)}</div><form onSubmit={e=>{e.preventDefault();send()}}><label>Instruction en français<input value={input} onChange={e=>setInput(e.target.value)} placeholder={context==='robots'?'R001 uniquement Coca-Cola':'Ajoute 10 Coca-Cola'}/></label><button disabled={!input.trim()} type="submit">Analyser</button></form>{pending&&<div className="copilot-confirm"><p>Cette opération modifie votre entrepôt. Les contraintes seront revérifiées au moment de la confirmation.</p><button className="primary" onClick={()=>{const plan=parseCopilot(engine,pending);if(plan.execute){const r=plan.execute();report(r);setMessages(m=>[...m,`${r.ok?'Action exécutée':'Action impossible'} : ${r.message}`]);if(r.ok&&plan.targetIds?.length)focus?.(plan.targetIds)}else setMessages(m=>[...m,plan.message]);setPending('')}}>Confirmer l’opération</button><button onClick={()=>setPending('')}>Annuler</button></div>}<details><summary>Exemples reconnus</summary>{(context==='robots'?['Le robot 1 peut chercher uniquement du Coca-Cola.','R002 peut récupérer tous les produits.','R003 travaille seulement sur A-1 et A-2.','Quel robot peut récupérer du Fanta ?','Envoie R001 chercher 5 Coca-Cola.']:['Crée un produit Fanta.','Ajoute 10 Coca-Cola.','Mets 20 Fanta dans A-2.','Dans quelle case se trouve le Coca-Cola ?','Crée une commande urgente de 5 Coca-Cola depuis A-1.','Montre-moi les rayonnages presque vides.']).map(text=><p key={text}>{text}</p>)}</details></section>}</div>;
}
