import {MAX_STOCK,MAX_CAPACITY,MAX_ORDER,safeQuantity} from './limits';
import { findPath, type Point } from './pathfinding';
import { emitSignal, explain, instrumentStep } from './telemetry';
import type { Assignment, Decision, RouteChange, Signal } from './telemetry';
export { findPath, type Point } from './pathfinding';
export type TileKind = 'shelf' | 'depot' | 'charger' | 'wall';
export type RobotState = 'idle' | 'to-pickup' | 'loading' | 'carrying' | 'unloading' | 'to-charge' | 'charging' | 'waiting' | 'blocked' | 'fault';
export interface Product { sku: string; name: string; value: number; color: string; size: number }
export interface StockMovement { tick: number; quantity: number; reason: string; robotId?: string; orderId?: string }
export interface Tile extends Point { id: string; kind: TileKind; sku?: string; stock?: number; location?: string; capacity?: number|null; allowedRobots?: string[]; priorityRobot?: string; movements?: StockMovement[] }
export interface OrderOptions { sourceId?: string; robotId?: string; depotId?: string }
export interface Robot extends Point { allowedProducts?:string[]; code?: string; disabled?: boolean; allowedLocations?: string[]; priorityLocations?: string[]; id: string; previousX: number; previousY: number; orientation: number; battery: number; state: RobotState; path: Point[]; cargo: number; orderId?: string; shelfId?: string; destination?: Point; distance: number; waitTicks: number; timer: number; history: string[]; waitingNow?: boolean; assignment?: Assignment; decision?: Decision; previousRoute?: RouteChange }
export interface Order extends OrderOptions { unitValue?: number; id: string; sku: string; quantity: number; priority: number; status: 'pending' | 'active' | 'completed' | 'blocked'; createdAt: number; completedAt?: number; income?: number; blockReason?: string; assignments?: { robotId: string; tick: number }[]; delivered: number; reserved: number; history: string[] }
export interface Metrics { completed: number; pending: number; active: number; activeRobots: number; idleRobots: number; charging: number; faults: number; averageTime: number; distance: number; energy: number; revenue: number; costs: number; profit: number; throughput: number; waiting: number }
export interface SimulationState { supplyMode?:'paid'|'free'; subsidizedSupply?:number; robotCodeCounter?:number; products?: Product[]; locationCounter?: number; managementVersion?: 2; version: 1; width: number; height: number; tick: number; seed: number; nextId: number; robots: Robot[]; tiles: Tile[]; orders: Order[]; budget: number; revenue: number; costs: number; energy: number; distance: number; events: { id: number; tick: number; level: 'info' | 'warning' | 'error'; message: string }[]; history: (Metrics & { tick: number })[]; strategy: 'balanced' | 'nearest'; signals?: Signal[]; signalCounter?: number; }
export type Result = { ok: boolean; message: string };
const key = (p: Point) => `${p.x},${p.y}`;
const distance = (a: Point, b: Point) => Math.abs(a.x-b.x)+Math.abs(a.y-b.y);
export const PRICES = { robot: 1400, shelf: 240, depot: 650, charger: 480, wall: 20, repair: 90, stockUnit: 8 };
export const PRODUCTS = [{ sku: 'A', name: 'Pièces de précision', value: 85 }, { sku: 'B', name: 'Capteurs intelligents', value: 110 }, { sku: 'C', name: 'Modules de contrôle', value: 145 }];


export class Engine {
  state: SimulationState;
  constructor(seed=42,options:{demo?:boolean}={}) {
    this.state={version:1,width:24,height:16,tick:0,seed:seed>>>0,nextId:1,robots:[],tiles:[],orders:[],budget:12500,revenue:0,costs:0,energy:0,distance:0,events:[],history:[],strategy:'balanced'};
    for(const x of [5,8,11,14,17]) for(const y of [3,4,5,7,8,9,11,12]) this.state.tiles.push({id:this.id('S'),kind:'shelf',x,y,sku:PRODUCTS[(x+y)%3].sku,stock:options.demo?12:0,capacity:options.demo?500:null});
    for(const y of [4,8,12]) this.state.tiles.push({id:this.id('D'),kind:'depot',x:22,y});
    for(const y of [3,6,9,12]) this.state.tiles.push({id:this.id('C'),kind:'charger',x:1,y});
    for(let i=0;i<6;i++) this.addRobot({x:3,y:3+i*2},95-i*6);
    this.initializeManagement();if(options.demo)this.generateOrders(12);this.log('info',options.demo?'SWARM online · deterministic demo ready':'Entrepôt prêt : zéro commande. Créez vos produits, approvisionnez puis commandez.');
  }
  private id(prefix:string) { return `${prefix}${String(this.state.nextId++).padStart(3,'0')}`; }
  private random() { this.state.seed=(1664525*this.state.seed+1013904223)>>>0;return this.state.seed/4294967296; }
  private log(level:'info'|'warning'|'error',message:string) { this.state.events.unshift({id:this.state.nextId++,tick:this.state.tick,level,message});this.state.events=this.state.events.slice(0,160); }
  private result(ok:boolean,message:string):Result { if(!ok)this.log('warning',message);return {ok,message}; }
  private solid() {return new Set(this.state.tiles.filter(t=>t.kind==='wall'||t.kind==='shelf').map(key));}
  private route(a:Point,b:Point,occupied=false,robotId?:string) {const blocked=this.solid();if(occupied)for(const r of this.state.robots)if(r.id!==robotId)blocked.add(key(r));return findPath(a,b,this.state.width,this.state.height,blocked);}
  private targets(tile:Tile) {return tile.kind==='shelf'?[{x:tile.x-1,y:tile.y},{x:tile.x+1,y:tile.y},{x:tile.x,y:tile.y-1},{x:tile.x,y:tile.y+1}].filter(p=>p.x>=0&&p.y>=0&&p.x<this.state.width&&p.y<this.state.height&&!this.solid().has(key(p))):[tile];}
  private nearest(robot:Robot,tiles:Tile[],occupied=false) {let best:{tile:Tile;point:Point;path:Point[]}|undefined;for(const tile of tiles)for(const point of this.targets(tile)){if(best&&distance(robot,point)>=best.path.length)continue;const path=this.route(robot,point,occupied,robot.id);if(path&&(!best||path.length<best.path.length))best={tile,point,path};}return best;}
  private addRobot(p:Point,battery=100) {this.state.robots.push({id:this.id('R'),...p,previousX:p.x,previousY:p.y,orientation:0,battery,state:'idle',path:[],cargo:0,distance:0,waitTicks:0,timer:0,history:[]});}
  createOrder(sku='A',quantity=1,priority=2,options:OrderOptions={}):Result {const validation=this.orderValidation(sku,quantity,priority,options);if(!validation.ok)return this.result(false,validation.message);return this.enqueueOrder(sku,quantity,priority,options);}
  private enqueueOrder(sku:string,quantity:number,priority:number,options:OrderOptions={}):Result {if(!this.products.some(p=>p.sku===sku)||!safeQuantity(quantity,MAX_ORDER)||!Number.isInteger(priority)||priority<1||priority>3)return this.result(false,'Produit ou quantité invalide.');if(this.state.orders.filter(o=>o.status!=='completed').length>=200)return this.result(false,'Queue limit: 200 open orders.');if(this.state.orders.length>=2000)return this.result(false,'Archive limit reached (2000 orders). Reset scenario to start a fresh session.');this.state.orders.push({...options,unitValue:this.products.find(p=>p.sku===sku)!.value,id:this.id('O'),sku,quantity,priority,status:'pending',createdAt:this.state.tick,delivered:0,reserved:0,history:['Order created']});return this.result(true,'Order added to dispatch queue.');}
  generateOrders(count:number):Result {if(!Number.isInteger(count)||count<1||count>100)return this.result(false,'Generate between 1 and 100 orders.');let added=0;for(let i=0;i<count;i++)if(this.enqueueOrder(PRODUCTS[Math.floor(this.random()*3)].sku,1+Math.floor(this.random()*3),1+Math.floor(this.random()*3)).ok)added++;return this.result(added>0,`${added} of ${count} orders generated.`);}
  buyRobot():Result {if(this.state.robots.length>=24)return this.result(false,'Fleet limit: 24 robots.');if(this.state.budget<PRICES.robot)return this.result(false,'Insufficient funds.');for(let y=1;y<15;y++)for(let x=1;x<4;x++)if(!this.solid().has(`${x},${y}`)&&!this.state.robots.some(r=>r.x===x&&r.y===y)){this.spend(PRICES.robot);this.addRobot({x,y});this.initializeManagement();this.log('info','Robot purchased and deployed');return this.result(true,'Robot deployed.');}return this.result(false,'No clear deployment cell.');}
  private spend(amount:number){if(amount>=20)emitSignal(this.state,{kind:'purchase',amount:-amount,x:0,y:0});const before=this.state.budget;this.state.budget-=amount;this.state.costs+=amount;if(before>=0&&this.state.budget<0)this.log('warning','Operating balance below zero · purchases suspended until deliveries restore funds.');}
  place(kind:TileKind,x:number,y:number):Result {if(!['shelf','depot','charger','wall'].includes(kind)||!Number.isInteger(x)||!Number.isInteger(y)||x<0||y<0||x>=24||y>=16)return this.result(false,'Choose a cell inside the warehouse.');if(this.state.tiles.some(t=>t.x===x&&t.y===y)||this.state.robots.some(r=>r.x===x&&r.y===y))return this.result(false,'Cell is occupied.');if(this.state.budget<PRICES[kind])return this.result(false,'Insufficient funds.');this.spend(PRICES[kind]);this.state.tiles.push({id:this.id('T'),kind,x,y,...(kind==='shelf'?{sku:'A',stock:0,capacity:null}:{})});this.initializeManagement();this.invalidate();return this.result(true,`${kind} installed.`);}
  removeAt(x:number,y:number):Result {const tile=this.state.tiles.find(t=>t.x===x&&t.y===y);if(!tile)return this.result(false,'No equipment here.');if(tile.kind==='shelf'&&(tile.stock??0)>0)return this.result(false,'Videz le stock avant de supprimer cet emplacement.');if(this.state.orders.some(o=>o.sourceId===tile.id&&o.status!=='completed'))return this.result(false,'Une commande référence cet emplacement.');if(this.state.robots.some(r=>r.shelfId===tile.id))return this.result(false,'Shelf has an active reservation.');if(this.state.orders.some(o=>o.depotId===tile.id&&o.status!=='completed'))return this.result(false,'Ce dépôt est la destination choisie d’une commande ouverte.');this.state.tiles=this.state.tiles.filter(t=>t!==tile);for(const r of this.state.robots){if(r.allowedLocations)r.allowedLocations=r.allowedLocations.filter(id=>id!==tile.id);if(r.priorityLocations)r.priorityLocations=r.priorityLocations.filter(id=>id!==tile.id);}this.invalidate();return this.result(true,'Equipment removed.');}
  private invalidate(){for(const r of this.state.robots){if(r.path.length){const blocked=r.path.some(p=>this.solid().has(key(p)));r.previousRoute={tick:this.state.tick,path:[{x:r.x,y:r.y},...r.path.map(p=>({...p}))],reason:blocked?'Un équipement bloque l’ancien trajet.':'Configuration modifiée : l’ancien trajet est recalculé.'};explain(r,this.state,'reroute',r.previousRoute.reason);emitSignal(this.state,{kind:'reroute',robotId:r.id,x:r.x,y:r.y});}r.path=[];}this.log('info','Layout changed · routes recalculating');const depots=this.state.tiles.filter(t=>t.kind==='depot');const chargers=this.state.tiles.filter(t=>t.kind==='charger');if(!depots.length)this.log('warning','No delivery depot · all deliveries are blocked.');else if(this.state.robots.some(r=>!this.nearest(r,depots)))this.log('warning','Layout disconnects a robot from all delivery depots.');if(!chargers.length)this.log('warning','No charging stations · fleet cannot replenish energy.');else if(this.state.robots.some(r=>!this.nearest(r,chargers)))this.log('warning','Layout disconnects a robot from all charging stations.');}
  removeRobot(id:string):Result {const r=this.state.robots.find(r=>r.id===id);if(!r)return this.result(false,'Robot not found.');if(r.cargo)return this.result(false,'Deliver secured cargo before removing this robot.');this.release(r);this.state.robots=this.state.robots.filter(robot=>robot.id!==id);for(const t of this.state.tiles){if(t.allowedRobots)t.allowedRobots=t.allowedRobots.filter(robot=>robot!==id);if(t.priorityRobot===id)t.priorityRobot=undefined;}for(const o of this.state.orders)if(o.robotId===id)o.robotId=undefined;return this.result(true,'Robot retired without refund.');}
  setPriority(id:string,priority:number):Result {const o=this.state.orders.find(o=>o.id===id);if(!o||!Number.isInteger(priority)||priority<1||priority>3)return this.result(false,'Invalid order or priority.');o.priority=priority;return this.result(true,'Priority updated.');}
  restock(sku:string,quantity:number):Result {const shelf=this.state.tiles.find(t=>t.kind==='shelf'&&t.sku===sku&&this.stockInfo(t).total+quantity<=this.stockCapacity(t,sku));if(!shelf)return this.result(false,'Aucun emplacement avec assez de capacité.');return this.adjustStock(shelf.id,quantity);}
  faultRobot(id:string):Result {const r=this.state.robots.find(r=>r.id===id);if(!r)return this.result(false,'Robot not found.');if(r.state==='fault')return this.result(false,'Robot is already offline.');this.release(r);r.state='fault';r.path=[];explain(r,this.state,'fault',r.cargo?'Robot immobilisé. Le colis reste à bord jusqu’à réparation.':'Robot immobilisé. Réservation libérée : un autre robot peut prendre la mission.');emitSignal(this.state,{kind:'fault',robotId:r.id,x:r.x,y:r.y});this.log('warning',`${r.code??id} offline · cargo secured, unpicked work redistributed`);return this.result(true,'Robot stopped.');}
  repairRobot(id:string):Result {const r=this.state.robots.find(r=>r.id===id);if(!r||r.state!=='fault')return this.result(false,'Select a failed robot.');if(this.state.budget<PRICES.repair)return this.result(false,'Budget insuffisant pour la réparation.');this.spend(PRICES.repair);r.battery=Math.max(25,r.battery);r.disabled=false;r.state=r.cargo?'carrying':'idle';this.log('info',`${r.code??r.id} réparé · ${PRICES.repair} €`);return this.result(true,'Robot repaired.');}
  setBattery(id:string,value:number):Result {const r=this.state.robots.find(r=>r.id===id);if(!r||!Number.isFinite(value)||value<0||value>100)return this.result(false,'Battery must be 0–100%.');r.battery=value;if(value===0)this.faultRobot(id);return this.result(true,'Battery updated.');}
  chargeRobot(id:string):Result {const r=this.state.robots.find(r=>r.id===id);if(!r||r.state==='fault')return this.result(false,'Robot unavailable.');if(r.cargo)return this.result(false,'Finish delivery before charging.');this.release(r);r.state='to-charge';r.destination=undefined;r.path=[];explain(r,this.state,'charging','Recharge demandée : mission non prélevée libérée, recherche d’une borne accessible.');return this.result(true,'Charging requested.');}
  private release(r:Robot){if(r.orderId&&!r.cargo){const order=this.state.orders.find(o=>o.id===r.orderId);if(order)order.reserved=Math.max(0,order.reserved-1);r.orderId=undefined;r.shelfId=undefined;}r.destination=undefined;r.path=[];}
  private dispatch(){
    const orders=this.state.orders.filter(o=>o.status!=='completed').sort((a,b)=>b.priority-a.priority||a.createdAt-b.createdAt);
    const routeCache=new Map<string,ReturnType<Engine['nearest']>>(),depotCache=new Map<string,boolean>();
    for(const o of orders){
      if(o.delivered+o.reserved>=o.quantity)continue;
      const shelves=this.state.tiles.filter(t=>t.kind==='shelf'&&t.sku===o.sku&&(!o.sourceId||t.id===o.sourceId)&&this.stockInfo(t).available>0);
      if(!shelves.length||!this.state.tiles.some(t=>t.kind==='depot'&&(!o.depotId||o.depotId===t.id))){o.status=o.reserved?'active':'blocked';o.blockReason=!shelves.length?'Stock disponible insuffisant : réapprovisionnez ce produit.':'Dépôt de destination absent : installez-le ou modifiez la commande.';continue;}
      const admissible=this.state.robots.filter(r=>!r.disabled&&(!o.robotId||o.robotId===r.id)&&shelves.some(t=>this.isAuthorized(r,t)));
      const candidates=admissible.filter(r=>r.state==='idle'&&r.battery>25).filter(r=>{const k=r.id+':'+(o.depotId??'*');if(!depotCache.has(k))depotCache.set(k,!!this.nearest(r,this.state.tiles.filter(t=>t.kind==='depot'&&(!o.depotId||t.id===o.depotId))));return depotCache.get(k)}).map(r=>{
        const permitted=shelves.filter(t=>this.isAuthorized(r,t));const cacheKey=r.id+':'+permitted.map(t=>t.id).join(',');
        if(!routeCache.has(cacheKey)){const preferred=this.nearest(r,permitted.filter(t=>t.priorityRobot===r.id||(r.priorityLocations??[]).includes(t.id)));routeCache.set(cacheKey,preferred&&r.battery>preferred.path.length*.18+20?preferred:this.nearest(r,permitted));}const target=routeCache.get(cacheKey);
        const preferred=target&&(target.tile.priorityRobot===r.id||(r.priorityLocations??[]).includes(target.tile.id));
        return {r,target,preferred,score:target?target.path.length+(this.state.strategy==='balanced'?(100-r.battery)*.12:0):Infinity};
      }).filter(c=>c.target&&c.r.battery>c.target.path.length*.18+20).sort((a,b)=>Number(b.preferred)-Number(a.preferred)||a.score-b.score);
      const c=candidates[0];if(!c){o.status=o.reserved?'active':!admissible.length||admissible.some(r=>r.state==='idle'&&r.battery>25)?'blocked':'pending';o.blockReason=!admissible.length?'Aucun robot autorisé pour cette source.':admissible.some(r=>r.state==='idle'&&r.battery>25)?'Aucun trajet accessible ou autonomie insuffisante.':'Robots autorisés occupés, hors service ou en recharge.';continue;}
      const r=c.r;r.orderId=o.id;r.shelfId=c.target!.tile.id;r.destination=c.target!.point;r.path=c.target!.path;r.state='to-pickup';r.assignment={tick:this.state.tick,strategy:this.state.strategy,score:c.score,distance:c.target!.path.length,battery:r.battery,candidates:candidates.length,priority:o.priority};
      explain(r,this.state,'assignment',`${c.preferred?'Robot prioritaire admissible. ':''}${o.robotId?'Robot demandé par la commande. ':''}Choisi parmi ${candidates.length} robot(s) admissibles : ${this.state.strategy==='nearest'?'trajet le plus court':'score distance + batterie'} = ${c.score.toFixed(2)} (${c.target!.path.length} m, ${r.battery.toFixed(0)} %).`);
      this.log('info',`${r.code??r.id} → ${o.id} · ${c.target!.tile.location} · ${r.decision!.message}`);r.history.unshift(`Assigned ${o.id}`);r.history=r.history.slice(0,20);o.blockReason=undefined;o.assignments=[...(o.assignments??[]),{robotId:r.id,tick:this.state.tick}].slice(-80);o.reserved++;o.status='active';
    }
  }
  tick(count=1){if(!Number.isInteger(count)||count<1||count>1000)throw new Error('Tick count must be 1–1000');for(let i=0;i<count;i++){const before=this.state.robots.map(r=>({...r,path:r.path.map(p=>({...p})),destination:r.destination?{...r.destination}:undefined}));const revenue=this.state.revenue;this.step();instrumentStep(this.state,before,revenue);}}
  private step(){this.state.tick++;this.dispatch();const robots=this.state.robots;const occupied=new Set(robots.map(key));const ordered=[...robots].sort((a,b)=>((parseInt(a.id.slice(1))+this.state.tick)%robots.length)-((parseInt(b.id.slice(1))+this.state.tick)%robots.length));for(const r of ordered){r.previousX=r.x;r.previousY=r.y;if(r.state==='fault')continue;if(r.battery<=0){this.faultRobot(r.id);continue;}if(r.state==='idle'){
  if(r.battery<30)r.state='to-charge';else {
    const mustYield=this.state.tiles.some(t=>t.x===r.x&&t.y===r.y&&(t.kind==='depot'||t.kind==='charger'))||robots.some(other=>other.id!==r.id&&((other.destination&&key(other.destination)===key(r))||other.path.slice(0,4).some(p=>key(p)===key(r))));
    if(mustYield){const free=[{x:r.x+1,y:r.y},{x:r.x,y:r.y-1},{x:r.x,y:r.y+1},{x:r.x-1,y:r.y}].find(p=>p.x>=0&&p.y>=0&&p.x<24&&p.y<16&&!occupied.has(key(p))&&!this.solid().has(key(p))&&!this.state.tiles.some(t=>t.x===p.x&&t.y===p.y));if(free){occupied.delete(key(r));occupied.add(key(free));r.orientation=Math.atan2(free.y-r.y,free.x-r.x);r.x=free.x;r.y=free.y;r.distance++;this.state.distance++;r.battery=Math.max(0,r.battery-.12);this.state.energy+=.12;this.spend(.004);}}
    continue;
  }
}
      if(r.state==='charging'){if(!this.state.tiles.some(t=>t.kind==='charger'&&key(t)===key(r))){r.state='to-charge';r.destination=undefined;continue;}const amount=Math.min(1.2,100-r.battery);r.battery+=amount;this.spend(amount*.025);if(r.battery>=99){r.state='idle';r.destination=undefined;}continue;}
      if(r.state==='loading'){if(--r.timer>0)continue;const s=this.state.tiles.find(t=>t.id===r.shelfId);if(!s||(s.stock??0)<1){this.release(r);r.state='idle';continue;}s.stock!--;this.recordMovement(s,-1,'Prélèvement',r.id,r.orderId);r.cargo=1;r.state='carrying';r.destination=undefined;r.path=[];continue;}
      if(r.state==='unloading'){if(!this.state.tiles.some(t=>t.kind==='depot'&&key(t)===key(r))){r.state='carrying';r.destination=undefined;continue;}if(--r.timer>0)continue;const o=this.state.orders.find(o=>o.id===r.orderId);if(o){o.delivered+=r.cargo;o.reserved-=r.cargo;if(o.delivered===o.quantity){o.status='completed';o.completedAt=this.state.tick;const income=o.quantity*(o.unitValue??this.products.find(p=>p.sku===o.sku)?.value??85);o.income=income;this.state.revenue+=income;this.state.budget+=income;o.history.push('Delivered');this.log('info',`${o.id} delivered · +${income} credits`);}}r.cargo=0;r.orderId=undefined;r.shelfId=undefined;r.destination=undefined;r.path=[];r.state='idle';continue;}
      if(r.cargo){r.state='carrying';const target=this.nearest(r,this.state.tiles.filter(t=>t.kind==='depot'&&(!this.state.orders.find(o=>o.id===r.orderId)?.depotId||t.id===this.state.orders.find(o=>o.id===r.orderId)?.depotId)),true)??this.nearest(r,this.state.tiles.filter(t=>t.kind==='depot'&&(!this.state.orders.find(o=>o.id===r.orderId)?.depotId||t.id===this.state.orders.find(o=>o.id===r.orderId)?.depotId)));if(target){r.destination=target.point;r.path=target.path;}else{r.waitTicks++;r.state='blocked';continue;}}
      else if(r.state==='to-charge'||(!r.orderId&&['waiting','blocked'].includes(r.state))){r.state='to-charge';const target=this.nearest(r,this.state.tiles.filter(t=>t.kind==='charger'),true);if(!target){r.state='waiting';r.waitTicks++;continue;}r.destination=target.point;r.path=target.path;}
      if(!r.destination){r.state='idle';continue;}if(key(r)===key(r.destination)){if(r.state==='to-charge')r.state='charging';else if(r.cargo){r.state='unloading';r.timer=3;}else{r.state='loading';r.timer=3;}continue;}
      if(!r.path.length||this.solid().has(key(r.path[0]))||occupied.has(key(r.path[0]))){const dynamic=this.solid();for(const k of occupied)if(k!==key(r))dynamic.add(k);r.path=findPath(r,r.destination,24,16,dynamic)??this.route(r,r.destination)??[];}
      const next=r.path[0];if(!next||occupied.has(key(next))){r.waitTicks++;
        if(next&&r.waitTicks%8===0){const directions=[[1,0],[0,1],[-1,0],[0,-1]];const offset=(this.state.tick+parseInt(r.id.slice(1)))%4;const escape=[...directions.slice(offset),...directions.slice(0,offset)].map(([dx,dy])=>({x:r.x+dx,y:r.y+dy})).find(p=>p.x>=0&&p.y>=0&&p.x<24&&p.y<16&&!occupied.has(key(p))&&!this.solid().has(key(p)));if(escape){occupied.delete(key(r));occupied.add(key(escape));r.orientation=Math.atan2(escape.y-r.y,escape.x-r.x);r.x=escape.x;r.y=escape.y;r.path=[];r.distance++;this.state.distance++;const energy=r.cargo?.18:.12;r.battery=Math.max(0,r.battery-energy);this.state.energy+=energy;this.spend(.004);}}
        if(r.waitTicks%80===0)this.log('warning',`${r.id} waiting · destination blocked`);continue;}
      // Sequential destination reservations forbid same-cell collisions and edge swaps.
      occupied.delete(key(r));occupied.add(key(next));r.path.shift();r.orientation=Math.atan2(next.y-r.y,next.x-r.x);r.x=next.x;r.y=next.y;r.distance++;this.state.distance++;const energy=r.cargo?.18:.12;r.battery=Math.max(0,r.battery-energy);this.state.energy+=energy;this.spend(.004);
    }if(this.state.tick%20===0){this.state.history.push({...this.metrics,tick:this.state.tick});this.state.history=this.state.history.slice(-120);}}
  get metrics():Metrics {const s=this.state,done=s.orders.filter(o=>o.status==='completed');return {completed:done.length,pending:s.orders.filter(o=>o.status==='pending'||o.status==='blocked').length,active:s.orders.filter(o=>o.status==='active').length,activeRobots:s.robots.filter(r=>!['idle','fault','charging','waiting'].includes(r.state)).length,idleRobots:s.robots.filter(r=>r.state==='idle').length,charging:s.robots.filter(r=>r.state==='charging').length,faults:s.robots.filter(r=>r.state==='fault').length,averageTime:done.length?done.reduce((sum,o)=>sum+(o.completedAt!-o.createdAt)*.5,0)/done.length:0,distance:s.distance,energy:s.energy,revenue:s.revenue,costs:s.costs,profit:s.revenue-s.costs,throughput:s.tick?done.length/(s.tick*.5)*3600:0,waiting:s.robots.reduce((sum,r)=>sum+r.waitTicks,0)};}
  get products():Product[]{return this.state.products??PRODUCTS.map((p,i)=>({...p,color:['#89b9d9','#b6a2d9','#d5b488'][i],size:1}));}
  private initializeManagement(){
    this.state.products??=PRODUCTS.map((p,i)=>({...p,color:['#89b9d9','#b6a2d9','#d5b488'][i],size:1}));this.state.locationCounter??=0;this.state.managementVersion=2;
    const used=new Set(this.state.tiles.map(t=>t.location).filter(Boolean));
    for(const t of this.state.tiles.filter(t=>t.kind==='shelf')){if(!t.location){let label:string;do{const n=this.state.locationCounter++;let column=Math.floor(n/8)+1,letters='';while(column){column--;letters=String.fromCharCode(65+column%26)+letters;column=Math.floor(column/26);}label=`${letters}-${n%8+1}`;}while(used.has(label));t.location=label;used.add(label);}if(t.capacity===undefined)t.capacity=Math.max(500,t.stock??0);t.movements??=[];}
    this.state.robotCodeCounter??=Math.max(0,...this.state.robots.map(r=>Number(r.code?.slice(1)??0)));const codes=new Set(this.state.robots.map(r=>r.code));for(const r of this.state.robots)if(!r.code){let code:string;do{code=`R${String(++this.state.robotCodeCounter).padStart(3,'0')}`;}while(codes.has(code));r.code=code;codes.add(code);}
  }
  stockInfo(t:Tile){const reserved=this.state.robots.filter(r=>r.shelfId===t.id&&!r.cargo&&r.orderId).length;return {total:t.stock??0,reserved,available:Math.max(0,(t.stock??0)-reserved)};}
  isAuthorized(r:Robot,t:Tile){return (!r.allowedProducts||r.allowedProducts.includes(t.sku??''))&&(!t.allowedRobots||t.allowedRobots.includes(r.id))&&(!r.allowedLocations||r.allowedLocations.includes(t.id));}
  missionReadyRobots(sku:string,options:OrderOptions={}){return this.eligibleRobots(sku,options).filter(r=>{if(r.battery<=25)return false;const shelves=this.state.tiles.filter(t=>t.kind==='shelf'&&t.sku===sku&&(!options.sourceId||t.id===options.sourceId)&&this.stockInfo(t).available>0&&this.isAuthorized(r,t));return shelves.some(t=>{const pickup=this.nearest(r,[t]);return pickup&&r.battery>pickup.path.length*.18+20&&this.nearest({...r,...pickup.point},this.state.tiles.filter(d=>d.kind==='depot'&&(!options.depotId||d.id===options.depotId)));});});}
  eligibleRobots(sku:string,options:OrderOptions={}){return this.state.robots.filter(r=>!r.disabled&&r.state!=='fault'&&(!options.robotId||options.robotId===r.id)&&this.state.tiles.some(t=>t.kind==='shelf'&&t.sku===sku&&(!options.sourceId||t.id===options.sourceId)&&this.stockInfo(t).available>0&&this.isAuthorized(r,t)));}
  canReachShelf(robot:Robot,tile:Tile){return !!this.nearest(robot,[tile]);}
  stockCapacity(tile:Tile,sku=tile.sku??''){return tile.capacity===null?MAX_STOCK:Math.min(MAX_STOCK,Math.floor((tile.capacity??500)/(this.products.find(p=>p.sku===sku)?.size??1)));}
  supplyCost(quantity:number){return this.state.supplyMode==='free'?0:quantity*PRICES.stockUnit;}
  setSupplyMode(free:boolean):Result {this.state.supplyMode=free?'free':'paid';this.log('info',free?'Sandbox activé : approvisionnement gratuit uniquement. Les autres dépenses restent payantes.':'Approvisionnement normal : marchandises payantes.');return {ok:true,message:free?'Sandbox : approvisionnement gratuit activé.':'Approvisionnement payant activé.'};}
  orderValidation(sku:string,quantity:number,priority=2,options:OrderOptions={}):Result {
    const fail=(message:string):Result=>({ok:false,message}),p=this.products.find(p=>p.sku===sku);
    if(!p)return fail('Choisissez un produit du catalogue.');
    if(!safeQuantity(quantity,MAX_ORDER))return fail(`Quantité invalide : entier de 1 à ${MAX_ORDER.toLocaleString('fr-FR')} unités attendu.`);
    if(!Number.isInteger(priority)||priority<1||priority>3)return fail('Choisissez une priorité de 1 à 3.');
    if(this.state.orders.filter(o=>o.status!=='completed').length>=200)return fail('Queue limit: 200 open orders.');
    if(this.state.orders.length>=2000)return fail('Archive limit reached (2000 orders). Reset scenario to start a fresh session.');
    if(options.sourceId&&!this.state.tiles.some(t=>t.id===options.sourceId&&t.kind==='shelf'&&t.sku===sku))return fail('Source incompatible avec ce produit.');
    const requested=options.robotId?this.state.robots.find(r=>r.id===options.robotId):undefined;
    if(options.robotId&&(!requested||requested.disabled||requested.state==='fault'))return fail(`Le robot ${requested?.code??options.robotId} est inconnu, en panne ou hors service.`);
    const shelves=this.state.tiles.filter(t=>t.kind==='shelf'&&t.sku===sku&&(!options.sourceId||t.id===options.sourceId)),stock=shelves.reduce((n,t)=>n+this.stockInfo(t).available,0);
    const robots=this.state.robots.filter(r=>!r.disabled&&r.state!=='fault'&&(!requested||r.id===requested.id));
    if(requested&&!shelves.some(t=>this.isAuthorized(requested,t)))return fail(options.sourceId?`Le robot ${requested.code} n’a pas accès au rayonnage ${shelves[0]?.location}.`:`Le robot ${requested.code} n’est pas autorisé à récupérer ${p.name}.`);
    if(stock<quantity)return fail(`Stock insuffisant : ${stock} ${p.name} disponibles pour ${quantity} demandés.`);
    const permitted=shelves.filter(t=>robots.some(r=>this.isAuthorized(r,t))),authorizedStock=permitted.reduce((n,t)=>n+this.stockInfo(t).available,0);
    if(!permitted.length)return fail('Aucun robot autorisé à récupérer ce produit.');
    if(authorizedStock<quantity)return fail(`Stock autorisé insuffisant : ${authorizedStock} unités accessibles aux robots choisis pour ${quantity} demandées.`);
    const depots=this.state.tiles.filter(t=>t.kind==='depot'&&(!options.depotId||t.id===options.depotId));
    if(!depots.length)return fail('Aucun dépôt accessible : installez un dépôt ou choisissez une destination existante.');
    const withDepot=robots.filter(r=>this.nearest(r,depots));if(!withDepot.length)return fail('Aucun dépôt accessible depuis les robots compatibles. Rouvrez un passage.');
    const ready=withDepot.filter(r=>r.battery>25);if(!ready.length)return fail('Autonomie insuffisante : rechargez un robot compatible avant de créer la commande.');
    let reachable=0;for(const t of permitted){if(ready.some(r=>{if(!this.isAuthorized(r,t))return false;const pickup=this.nearest(r,[t]);return pickup&&r.battery>pickup.path.length*.18+20;}))reachable+=this.stockInfo(t).available;if(reachable>=quantity)return {ok:true,message:`${quantity} ${p.name} à livrer progressivement, une unité par trajet. Les robots occupés attendent leur disponibilité.`};}
    return fail(`Stock accessible insuffisant : ${reachable} unités avec trajet, permissions et autonomie compatibles pour ${quantity} demandées.`);
  }
  createProduct(name:string,sku:string,value=85,color='#75d7e5',size=1):Result{
    name=name.trim();sku=sku.trim().toUpperCase();if(!name||name.length>60||!/^[-A-Z0-9_]{1,24}$/.test(sku)||!Number.isFinite(value)||value<0||value>100000||!/^#[0-9a-f]{6}$/i.test(color)||!Number.isInteger(size)||size<1||size>10)return this.result(false,'Nom, SKU, valeur, couleur ou encombrement invalide.');
    if(this.products.length>=100||this.products.some(p=>p.sku===sku||p.name.toLowerCase()===name.toLowerCase()))return this.result(false,'Produit déjà présent ou catalogue plein (100 produits).');
    this.state.products!.push({name,sku,value,color,size});this.log('info',`Produit créé : ${name} (${sku})`);return this.result(true,'Produit créé.');
  }
  configureShelf(id:string,sku:string,capacity:number|null):Result{
    const t=this.state.tiles.find(t=>t.id===id&&t.kind==='shelf'),p=this.products.find(p=>p.sku===sku);
    if(!t||!p||capacity!==null&&(!Number.isSafeInteger(capacity)||capacity<1||capacity>MAX_CAPACITY))return this.result(false,'Emplacement, produit ou capacité invalide.');
    if(t.sku!==sku&&((t.stock??0)>0||this.stockInfo(t).reserved))return this.result(false,'Videz les marchandises non réservées avant de changer de produit.');
    if(capacity!==null&&capacity<(t.stock??0)*p.size)return this.result(false,'Capacité inférieure au stock présent.');t.sku=sku;t.capacity=capacity;this.log('info',`${t.location} configuré pour ${p.name}`);return this.result(true,'Emplacement configuré.');
  }
  private recordMovement(t:Tile,quantity:number,reason:string,robotId?:string,orderId?:string){t.movements=[{tick:this.state.tick,quantity,reason,robotId,orderId},...(t.movements??[])].slice(0,100);}
  adjustStock(id:string,quantity:number):Result{
    const t=this.state.tiles.find(t=>t.id===id&&t.kind==='shelf');if(!t||!safeQuantity(Math.abs(quantity)))return this.result(false,`Choisissez un emplacement et une quantité entière de 1 à ${MAX_STOCK.toLocaleString('fr-FR')}.`);
    const info=this.stockInfo(t),p=this.products.find(p=>p.sku===t.sku)!;
    if(quantity<0&&-quantity>info.available)return this.result(false,'Impossible de retirer du stock réservé.');
    if(info.total+quantity>this.stockCapacity(t))return this.result(false,'Capacité de l’emplacement dépassée.');
    if(quantity>0){const cost=this.supplyCost(quantity);if(cost>0&&this.state.budget<cost)return this.result(false,`Budget insuffisant : ${cost} € nécessaires pour les marchandises. Le Sandbox permet un approvisionnement gratuit.`);if(cost)this.spend(cost);else this.state.subsidizedSupply=(this.state.subsidizedSupply??0)+quantity*PRICES.stockUnit;}
    t.stock=info.total+quantity;this.recordMovement(t,quantity,quantity>0?'Réapprovisionnement':'Retrait manuel sans remboursement');this.log('info',`${t.location} : ${quantity>0?'+':''}${quantity} ${p.name}`);return this.result(true,'Stock mis à jour.');
  }
  setShelfPermissions(id:string,allowed?:string[],priorityRobot?:string):Result{
    const t=this.state.tiles.find(t=>t.id===id&&t.kind==='shelf');if(!t||allowed?.some(id=>!this.state.robots.some(r=>r.id===id))||(priorityRobot&&!this.state.robots.some(r=>r.id===priorityRobot))||(priorityRobot&&allowed&&!allowed.includes(priorityRobot)))return this.result(false,'Autorisations ou robot prioritaire invalides.');
    t.allowedRobots=allowed?[...new Set(allowed)]:undefined;t.priorityRobot=priorityRobot;this.enforcePermissions();this.log('info',`Autorisations mises à jour : ${t.location}`);return this.result(true,'Permissions appliquées. Les colis déjà prélevés terminent leur livraison.');
  }
  setRobotProductPermissions(id:string,products?:string[]):Result{
    const r=this.state.robots.find(r=>r.id===id);if(!r||products&&(!Array.isArray(products)||products.some(sku=>!this.products.some(p=>p.sku===sku))))return this.result(false,'Produits autorisés invalides.');
    r.allowedProducts=products?[...new Set(products)]:undefined;this.enforcePermissions();this.log('info',`${r.code} : autorisations produits mises à jour`);return this.result(true,'Autorisations produits appliquées. Les colis chargés restent sécurisés.');
  }
  setRobotPermissions(id:string,allowed?:string[],priority:string[]=[]):Result{
    const r=this.state.robots.find(r=>r.id===id);if(!r||[...(allowed??[]),...priority].some(id=>!this.state.tiles.some(t=>t.kind==='shelf'&&t.id===id))||priority.some(id=>allowed&&!allowed.includes(id)))return this.result(false,'Zones invalides.');
    r.allowedLocations=allowed?[...new Set(allowed)]:undefined;r.priorityLocations=[...new Set(priority)];this.enforcePermissions();this.log('info',`Autorisations mises à jour : ${r.code}`);return this.result(true,'Zones mises à jour.');
  }
  private enforcePermissions(){for(const r of this.state.robots){const t=this.state.tiles.find(t=>t.id===r.shelfId);if(t&&!r.cargo&&!this.isAuthorized(r,t)){this.release(r);if(r.state!=='fault')r.state='idle';explain(r,this.state,'waiting','Autorisation retirée avant prélèvement : réservation libérée.');}}}
  setService(id:string,disabled:boolean):Result{const r=this.state.robots.find(r=>r.id===id);if(!r)return this.result(false,'Robot inconnu.');if(disabled){if(r.state==='fault'&&!r.disabled)return this.result(false,'Réparez la panne avant une suspension administrative.');if(r.state!=='fault')this.faultRobot(id);r.disabled=true;return this.result(true,'Robot hors service. Son colis reste sécurisé.');}if(r.state==='fault'&&!r.disabled)return this.result(false,'Ce robot est en panne : réparez-le.');r.disabled=false;if(r.state==='fault'){r.state=r.cargo?'carrying':'idle';r.battery=Math.max(1,r.battery);}return this.result(true,'Robot réactivé.');}
  cancelOrder(id:string):Result{const o=this.state.orders.find(o=>o.id===id);if(!o||o.status==='completed'||o.delivered||this.state.robots.some(r=>r.orderId===id&&r.cargo))return this.result(false,'Une commande prélevée ou livrée ne peut pas être annulée.');for(const r of this.state.robots.filter(r=>r.orderId===id)){this.release(r);if(r.state!=='fault')r.state='idle';}this.state.orders=this.state.orders.filter(order=>order!==o);this.log('info',`${id} annulée avant prélèvement`);return this.result(true,'Commande annulée.');}
  private validateManagement(){
    if(this.state.supplyMode!==undefined&&!['paid','free'].includes(this.state.supplyMode)||this.state.subsidizedSupply!==undefined&&(!Number.isFinite(this.state.subsidizedSupply)||this.state.subsidizedSupply<0))throw new Error('Mode économique invalide.');
    const products=this.products,skus=new Set<string>();if(products.length>100)throw new Error('Catalogue invalide.');for(const p of products){if(!p||!/^[-A-Z0-9_]{1,24}$/.test(p.sku)||skus.has(p.sku)||typeof p.name!=='string'||!p.name.trim()||p.name.length>60||!Number.isFinite(p.value)||p.value<0||p.value>100000||!/^#[0-9a-f]{6}$/i.test(p.color)||!Number.isInteger(p.size)||p.size<1||p.size>10)throw new Error('Produit invalide.');skus.add(p.sku);}
    const locations=new Set<string>(),codes=new Set<string>();const validRobot=(id:string)=>this.state.robots.some(r=>r.id===id),validShelf=(id:string)=>this.state.tiles.some(t=>t.kind==='shelf'&&t.id===id);
    for(const t of this.state.tiles.filter(t=>t.kind==='shelf')){if(!t.location||locations.has(t.location)||t.capacity!==null&&(!Number.isSafeInteger(t.capacity)||t.capacity!<1||t.capacity!>MAX_CAPACITY)||!skus.has(t.sku??'')||(t.stock??0)>this.stockCapacity(t)||this.stockInfo(t).reserved>(t.stock??0)||t.allowedRobots&&(!Array.isArray(t.allowedRobots)||t.allowedRobots.some(id=>!validRobot(id)))||t.priorityRobot&&!validRobot(t.priorityRobot))throw new Error('Emplacement invalide.');locations.add(t.location);if(!Array.isArray(t.movements)||t.movements.length>100||t.movements.some(m=>!Number.isInteger(m.tick)||m.tick<0||m.tick>this.state.tick||!Number.isInteger(m.quantity)||typeof m.reason!=='string'))throw new Error('Mouvements invalides.');}
    for(const r of this.state.robots){if(r.allowedProducts&&(!Array.isArray(r.allowedProducts)||r.allowedProducts.some(sku=>!skus.has(sku))))throw new Error('Permissions produits invalides.');if(!r.code||codes.has(r.code)||r.disabled!==undefined&&typeof r.disabled!=='boolean'||r.allowedLocations&&(!Array.isArray(r.allowedLocations)||r.allowedLocations.some(id=>!validShelf(id)))||r.priorityLocations&&(!Array.isArray(r.priorityLocations)||r.priorityLocations.some(id=>!validShelf(id))))throw new Error('Permissions robot invalides.');codes.add(r.code);const t=this.state.tiles.find(t=>t.id===r.shelfId);if(t&&!r.cargo&&!this.isAuthorized(r,t))throw new Error('Mission non autorisée.');}
    for(const o of this.state.orders)if(o.unitValue!==undefined&&(!Number.isFinite(o.unitValue)||o.unitValue<0)||o.status!=='completed'&&o.sourceId&&!validShelf(o.sourceId)||o.status!=='completed'&&o.robotId&&!validRobot(o.robotId)||o.status!=='completed'&&o.depotId&&!this.state.tiles.some(t=>t.kind==='depot'&&t.id===o.depotId))throw new Error('Contraintes de commande invalides.');
    if(!Number.isInteger(this.state.robotCodeCounter)||this.state.robotCodeCounter!<0)throw new Error('Compteur robots invalide.');if(!Number.isInteger(this.state.locationCounter)||this.state.locationCounter!<0)throw new Error('Compteur emplacements invalide.');
  }

  serialize(){return JSON.stringify(this.state);}
  static restore(json:string):Engine {let s:SimulationState;try{s=JSON.parse(json) as SimulationState;}catch{throw new Error('Save file is not valid JSON.');}if(!s||s.version!==1||s.width!==24||s.height!==16||!Array.isArray(s.robots)||s.robots.length>24||!Array.isArray(s.tiles)||!Array.isArray(s.orders)||s.orders.length>10000||!Number.isFinite(s.budget)||!Number.isInteger(s.tick)||s.tick<0)throw new Error('Save schema is invalid.');const positions=new Set<string>();const ids=new Set<string>();for(const item of [...s.tiles,...s.robots]){if(!Number.isInteger(item.x)||!Number.isInteger(item.y)||item.x<0||item.y<0||item.x>=24||item.y>=16||typeof item.id!=='string'||ids.has(item.id))throw new Error('Invalid entity in save.');ids.add(item.id);}const solid=new Set(s.tiles.filter(t=>t.kind==='shelf'||t.kind==='wall').map(key));for(const r of s.robots){if(positions.has(key(r))||solid.has(key(r))||!Number.isFinite(r.battery)||r.battery<0||r.battery>100||![0,1].includes(r.cargo)||!Array.isArray(r.path)||!['idle','to-pickup','loading','carrying','unloading','to-charge','charging','waiting','blocked','fault'].includes(r.state))throw new Error('Invalid robot state in save.');positions.add(key(r));}for(const t of s.tiles)if(!['shelf','wall','depot','charger'].includes(t.kind)||(t.kind==='shelf'&&(!Number.isSafeInteger(t.stock)||t.stock!<0||t.stock!>MAX_STOCK)))throw new Error('Invalid equipment in save.');for(const o of s.orders)if(!(s.products??PRODUCTS).some(p=>p.sku===o.sku)||!safeQuantity(o.quantity,MAX_ORDER)||o.delivered<0||o.reserved<0||o.delivered+o.reserved>o.quantity||!Number.isFinite(o.createdAt))throw new Error('Invalid order in save.');for(const r of s.robots)if(r.orderId&&!s.orders.some(o=>o.id===r.orderId))throw new Error('Missing robot order.');for(const o of s.orders)if(o.reserved!==s.robots.filter(r=>r.orderId===o.id).length)throw new Error('Invalid reservations.');if(!Number.isFinite(s.nextId)||!Number.isFinite(s.seed)||!Array.isArray(s.events)||!Array.isArray(s.history)||![s.costs,s.revenue,s.energy,s.distance].every(n=>Number.isFinite(n)&&n>=0))throw new Error('Invalid counters.');
    const validPoint=(p:Point)=>p&&Number.isInteger(p.x)&&Number.isInteger(p.y)&&p.x>=0&&p.y>=0&&p.x<24&&p.y<16;
    const validNumbers=(numbers:number[])=>numbers.every(n=>Number.isFinite(n)&&n>=0);
    if(!Number.isInteger(s.nextId)||s.nextId<1||!Number.isInteger(s.seed)||s.seed<0||s.events.length>160||s.history.length>120||!['balanced','nearest'].includes(s.strategy))throw new Error('Invalid simulation settings.');
    const tilePositions=new Set<string>();for(const t of s.tiles){if(tilePositions.has(key(t)))throw new Error('Duplicate equipment cell.');tilePositions.add(key(t));}
    for(const r of s.robots){if(!validNumbers([r.distance,r.waitTicks,r.timer])||!Number.isFinite(r.orientation)||!Number.isInteger(r.previousX)||!Number.isInteger(r.previousY)||!Array.isArray(r.history)||r.history.length>20||r.history.some(h=>typeof h!=='string')||(r.destination&&!validPoint(r.destination)))throw new Error('Invalid robot metadata.');let previous:Point=r;for(const p of r.path){if(!validPoint(p)||distance(previous,p)!==1)throw new Error('Invalid robot route.');previous=p;}if(r.cargo&&!r.orderId)throw new Error('Cargo has no order.');if(r.shelfId&&!s.tiles.some(t=>t.id===r.shelfId&&t.kind==='shelf'))throw new Error('Missing reserved shelf.');}
    const orderIds=new Set<string>();for(const o of s.orders){if(typeof o.id!=='string'||orderIds.has(o.id)||!['pending','active','blocked','completed'].includes(o.status)||![1,2,3].includes(o.priority)||!Number.isInteger(o.delivered)||!Number.isInteger(o.reserved)||!Array.isArray(o.history)||o.history.some(h=>typeof h!=='string')||(o.status==='completed'&&(o.delivered!==o.quantity||!Number.isFinite(o.completedAt))))throw new Error('Invalid order metadata.');orderIds.add(o.id);}
    for(const event of s.events)if(!event||!['info','warning','error'].includes(event.level)||typeof event.message!=='string'||!validNumbers([event.id,event.tick]))throw new Error('Invalid event log.');
    for(const sample of s.history)if(!sample||!validNumbers([sample.tick,sample.completed,sample.pending,sample.active,sample.distance,sample.energy,sample.costs,sample.revenue,sample.averageTime,sample.throughput,sample.waiting])||!Number.isFinite(sample.profit))throw new Error('Invalid metrics history.');
    if(s.signals!==undefined){if(!Array.isArray(s.signals)||s.signals.length>80||!Number.isInteger(s.signalCounter)||s.signalCounter!<0)throw new Error('Invalid decision signals.');for(const signal of s.signals)if(!signal||!validPoint(signal)||!Number.isInteger(signal.tick)||signal.tick<0||signal.tick>s.tick||typeof signal.id!=='string'||!['pickup','delivery','reward','purchase','reroute','fault'].includes(signal.kind)||(signal.amount!==undefined&&!Number.isFinite(signal.amount)))throw new Error('Invalid visual signal.');}for(const r of s.robots){if(r.decision&&(!Number.isInteger(r.decision.tick)||r.decision.tick<0||typeof r.decision.message!=='string'||!['assignment','reroute','charging','waiting','fault','pickup','delivery','idle'].includes(r.decision.kind)))throw new Error('Invalid decision metadata.');if(r.assignment&&(!validNumbers([r.assignment.tick,r.assignment.score,r.assignment.distance,r.assignment.battery,r.assignment.candidates,r.assignment.priority])||!['nearest','balanced'].includes(r.assignment.strategy)))throw new Error('Invalid assignment metadata.');if(r.previousRoute&&(!Number.isInteger(r.previousRoute.tick)||typeof r.previousRoute.reason!=='string'||!Array.isArray(r.previousRoute.path)||r.previousRoute.path.length>384||r.previousRoute.path.some(p=>!validPoint(p))))throw new Error('Invalid prior route.');}for(const r of s.robots)if(r.waitingNow!==undefined&&typeof r.waitingNow!=='boolean')throw new Error('Invalid waiting marker.');for(const o of s.orders)if(o.blockReason!==undefined&&(typeof o.blockReason!=='string'||o.blockReason.length>300))throw new Error('Invalid order explanation.');for(const o of s.orders)if(o.assignments&&(!Array.isArray(o.assignments)||o.assignments.length>80||o.assignments.some(a=>!a||typeof a.robotId!=='string'||!Number.isInteger(a.tick)||a.tick<0||a.tick>s.tick)))throw new Error('Invalid assignment history.');const engine=new Engine();engine.state=s;engine.initializeManagement();engine.validateManagement();return engine;}
}
