import {useState} from 'react';
import {Engine,PRICES} from './engine';
import type {Robot,Result} from './engine';
import Warehouse from './Warehouse';
import RobotInspector from './RobotInspector';
import {RobotZones,FleetList} from './Management';
import {money,robotStates} from './presentation';
import {transaction} from './operations';
type Props={engine:Engine;report:(r:Result)=>void;follow:(id:string)=>void;selected?:string|null;select?:(id:string|null)=>void;playing:boolean;speed:number;highlights?:string[]};
export default function FleetMap(props:Props){const {engine,report}=props;const [local,setLocal]=useState<string|null>(null),[tab,setTab]=useState('map'),[picking,setPicking]=useState(false),[draft,setDraft]=useState<string[]>([]);const id=props.selected??local,r=engine.state.robots.find(r=>r.id===id);
 const select=(id:string|null)=>{setPicking(false);setLocal(id);props.select?.(id)};
 const allowed=r?engine.state.tiles.filter(t=>t.kind==='shelf'&&engine.isAuthorized(r,t)).map(t=>t.id):[];
 const mapSelect=(id:string|null)=>{if(picking){if(engine.state.tiles.some(t=>t.id===id&&t.kind==='shelf'))setDraft(d=>d.includes(id!)?d.filter(x=>x!==id):[...d,id!]);return}if(engine.state.robots.some(r=>r.id===id))select(id);};
 return <section className="management-page map-management" data-testid="fleet-map"><div className="section-intro"><h1>Flotte de robots</h1><p>Sélectionnez un robot pour comprendre sa mission et choisir ce qu’il peut récupérer.</p></div><div className="tabs"><button aria-selected={tab==='map'} onClick={()=>setTab('map')}>Carte</button><button aria-selected={tab==='list'} onClick={()=>setTab('list')}>Liste détaillée</button><button onClick={()=>report(engine.buyRobot())}>Déployer un robot · {money(PRICES.robot)}</button></div>{tab==='list'?<FleetList engine={engine} report={report} follow={props.follow}/>:<div className="map-management-body"><div className="workspace-map">{picking&&<div className="selection-banner"><strong>Sélectionnez plusieurs rayonnages · {draft.length} choisis</strong><button className="primary" onClick={()=>{if(!r)return;const result=transaction(engine,copy=>{let result=copy.setRobotProductPermissions(r.id);if(result.ok)result=copy.setRobotPermissions(r.id,draft,(r.priorityLocations??[]).filter(id=>draft.includes(id)));return result});report(result);if(result.ok)setPicking(false)}}>Confirmer la sélection</button><button onClick={()=>setPicking(false)}>Annuler la sélection</button></div>}<Warehouse showLocations state={engine.state} selected={r?.id??null} select={mapSelect} highlighted={picking?draft:[...allowed,...(props.highlights??[])]} speed={props.speed} playing={props.playing} tool="select" onPlace={()=>{}}/></div><aside className="workspace-context"><h2>Vos robots</h2><div className="compact-fleet">{engine.state.robots.map(robot=><button key={robot.id} className={r?.id===robot.id?'selected':''} onClick={()=>select(robot.id)}><strong>{robot.code}</strong><span>{robot.disabled?'Hors service':robotStates[robot.state]}</span><small>{robot.battery.toFixed(0)} %</small></button>)}</div>{r?<><RobotPermissions key={r.id+JSON.stringify([r.allowedProducts,r.allowedLocations])} engine={engine} robot={r} report={report} pick={()=>{setDraft(r.allowedLocations??[]);setPicking(true)}}/><RobotInspector robot={r} state={engine.state} charge={()=>report(engine.chargeRobot(r.id))} fault={()=>report(r.state==='fault'?engine.repairRobot(r.id):engine.faultRobot(r.id))} retire={()=>{if(window.confirm('Retirer le robot sans remboursement ?'))report(engine.removeRobot(r.id))}}/><div className="robot-actions">{r.disabled?<button onClick={()=>report(engine.setService(r.id,false))}>Réactiver {r.code}</button>:r.state!=='fault'&&<button onClick={()=>report(engine.setService(r.id,true))}>Mettre hors service</button>}</div><details><summary>Missions et zones prioritaires</summary><RobotZones engine={engine} id={r.id} report={report}/>{engine.state.orders.filter(o=>o.assignments?.some(a=>a.robotId===r.id)).map(o=><p key={o.id}>{o.id} · {o.delivered}/{o.quantity} livrés</p>)}</details></>:<p className="hint">Cliquez sur un robot dans la carte ou la liste. Ses rayonnages autorisés apparaîtront en vert.</p>}</aside></div>}</section>;
}
function RobotPermissions({engine,robot,report,pick}:{engine:Engine;robot:Robot;report:(r:Result)=>void;pick:()=>void}){
 const [mode,setMode]=useState(robot.allowedProducts?'products':robot.allowedLocations?'locations':'all'),[products,setProducts]=useState(robot.allowedProducts??[]),[locations,setLocations]=useState(robot.allowedLocations??[]);
 const save=()=>report(transaction(engine,copy=>{let result=copy.setRobotProductPermissions(robot.id,mode==='products'?products:undefined);if(result.ok)result=copy.setRobotPermissions(robot.id,mode==='locations'?locations:undefined,(robot.priorityLocations??[]).filter(id=>mode!=='locations'||locations.includes(id)));return result}));
 return <section className="robot-permissions"><h2>Que peut récupérer ce robot ?</h2><label>Mode d’autorisation<select aria-label="Mode d’autorisation" value={mode} onChange={e=>setMode(e.target.value)}><option value="all">Tous les stocks</option><option value="products">Produits sélectionnés</option><option value="locations">Rayonnages sélectionnés</option></select></label>{mode==='products'&&<div className="permission-grid">{engine.products.map(p=><label className="check" key={p.sku}><input type="checkbox" checked={products.includes(p.sku)} onChange={e=>setProducts(e.target.checked?[...products,p.sku]:products.filter(s=>s!==p.sku))}/>{p.name}</label>)}</div>}{mode==='locations'&&<><button onClick={pick}>Sélectionner sur la carte</button><details><summary>Choisir dans la liste</summary><div className="permission-grid">{engine.state.tiles.filter(t=>t.kind==='shelf').map(t=><label className="check" key={t.id}><input type="checkbox" checked={locations.includes(t.id)} onChange={e=>setLocations(e.target.checked?[...locations,t.id]:locations.filter(id=>id!==t.id))}/>{t.location}</label>)}</div></details></>}<button className="primary full" onClick={save}>Enregistrer les autorisations</button><p className="hint">Ces limites s’ajoutent aux permissions des rayonnages. Une priorité reste une préférence. Les colis déjà à bord terminent leur livraison.</p></section>;
}
