import {useState} from 'react';
import {Bot,BatteryCharging,Construction,PackageX,Package,PlugZap,Warehouse as Depot,OctagonAlert,ShieldOff,Wrench} from 'lucide-react';
import type {Engine,Result} from './engine';
import {PRICES} from './engine';
import {INCIDENTS} from './incidents';
import type {IncidentName} from './incidents';
import {applyLabIncident,incidentResolved} from './labSession';
import type {LabIncident} from './labSession';
import Warehouse from './Warehouse';
import {frenchMessage} from './messages';
import {money,robotStates} from './presentation';
type Props={baseline:string;records:LabIncident[];engine:Engine;report:(r:Result)=>void;restore:(snapshot:string)=>void;guided:()=>void;arena:()=>void;build:(kind:string)=>void;playing:boolean;toggle:()=>void;speed:number;setSpeed:(n:number)=>void;compare:()=>void;comparison:React.ReactNode};
const descriptions=['Immobilisez un robot et observez la reprise de ses missions.','Abaissez sa batterie pour tester la recharge.','Placez un obstacle sur une case libre.','Ajoutez une série de vraies commandes.','Retirez le stock disponible en conservant les réservations.','Conservez une borne et provoquez une file de recharge.','Bloquez les abords d’un dépôt sans supprimer les colis.','Arrêtez un robot, même lorsqu’il transporte un colis.','Testez plusieurs arrêts simultanés.','Interdisez l’accès à un rayonnage.'];
const icons=[Wrench,BatteryCharging,Construction,Package,PackageX,PlugZap,Depot,Bot,OctagonAlert,ShieldOff];
export default function Lab(props:Props){const {engine,report,records}=props,s=engine.state;
 const [incident,setIncident]=useState<IncidentName>('Robot en panne'),[target,setTarget]=useState(s.robots[0]?.id??''),[count,setCount]=useState(3),[battery,setBattery]=useState(5),[cell,setCell]=useState<{x:number;y:number}>(),[stockMode,setStockMode]=useState('shelf'),[sku,setSku]=useState(engine.products[0]?.sku??''),[active,setActive]=useState(records.at(-1)?.id??''),[message,setMessage]=useState('');
 const type=['Robot en panne','Robot immobilisé','Batterie critique'].includes(incident)?'robot':['Rupture de stock','Zone interdite'].includes(incident)?'shelf':incident==='Station saturée'?'charger':incident==='Dépôt inaccessible'?'depot':undefined;
 const candidates=type==='robot'?s.robots.map(r=>({id:r.id,label:r.code??r.id})):s.tiles.filter(t=>t.kind===type).map(t=>({id:t.id,label:t.location??`${type==='charger'?'Borne':'Dépôt'} ${t.x+1}, ${t.y+1}`}));
 const choose=(name:IncidentName)=>{setIncident(name);setCell(undefined);const kind=['Robot en panne','Robot immobilisé','Batterie critique'].includes(name)?'robot':['Rupture de stock','Zone interdite'].includes(name)?'shelf':name==='Station saturée'?'charger':'depot';setTarget(kind==='robot'?s.robots.find(r=>r.state!=='fault')?.id??'':s.tiles.find(t=>t.kind===kind)?.id??'')};
 const record=records.find(r=>r.id===active),affectedRobots=record?s.robots.filter(r=>record.robots.includes(r.id)):[],affectedOrders=record?s.orders.filter(o=>record.orders.includes(o.id)):[];
 const select=(id:string|null)=>{if(type==='robot'&&s.robots.some(r=>r.id===id)||s.tiles.some(t=>t.kind===type&&t.id===id))setTarget(id??'')};
 const perform=()=>{const result=applyLabIncident(engine,incident,{target,count,battery,cell,sku:incident==='Rupture de stock'&&stockMode==='product'?sku:undefined},records);setMessage(frenchMessage(result.message));if(result.ok)setActive(records.at(-1)!.id);report(result)};
 const robotIncident=record&&['Robot en panne','Robot immobilisé','Pannes simultanées'].includes(record.name),batteryIncident=record?.name==='Batterie critique',wallsIncident=record&&['Passage bloqué','Dépôt inaccessible'].includes(record.name),stockIncident=record?.name==='Rupture de stock',stationIncident=record?.name==='Station saturée';
 return <section className="management-page lab-page"><div className="section-intro"><h1>SWARM LAB</h1><p>Choisissez un incident, cliquez sur sa cible, puis observez et résolvez ses conséquences réelles.</p></div><div className="tabs"><button onClick={props.guided}>Visite guidée · Démo intelligente</button><button aria-selected="true">Expérimentation libre</button><button onClick={()=>{if(window.confirm('Restaurer l’état initial de cette expérimentation ?')){props.restore(props.baseline);records.splice(0);setActive('');setMessage('État initial restauré.')}}}>Restaurer l’état initial du Lab</button></div>
 <div className="incident-cards">{INCIDENTS.map((name,i)=>{const Icon=icons[i];return <button className={incident===name?'selected':''} aria-pressed={incident===name} key={name} onClick={()=>choose(name)}><Icon size={20}/><strong>{name}</strong><span>{descriptions[i]}</span></button>})}</div>
 <div className="incident-controls"><strong>{incident}</strong>{type&&!(incident==='Rupture de stock'&&stockMode==='product')&&<label>{type==='robot'?'Robot cible':type==='shelf'?'Rayonnage cible':type==='charger'?'Station cible':'Dépôt cible'}<select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Choisir sur la carte</option>{candidates.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label>}{incident==='Rupture de stock'&&<><label>Type de cible<select value={stockMode} onChange={e=>setStockMode(e.target.value)}><option value="shelf">Rayonnage</option><option value="product">Produit · tous ses rayonnages</option></select></label>{stockMode==='product'&&<label>Produit cible<select value={sku} onChange={e=>setSku(e.target.value)}>{engine.products.map(p=><option key={p.sku} value={p.sku}>{p.name}</option>)}</select></label>}</>}{incident==='Batterie critique'&&<label>Niveau de batterie (%)<input type="number" min="0" max="20" value={battery} onChange={e=>setBattery(Number(e.target.value))}/></label>}{['Commandes massives','Pannes simultanées'].includes(incident)&&<label>{incident==='Commandes massives'?'Nombre de commandes':'Nombre de pannes'}<input type="number" min="1" max={incident==='Commandes massives'?100:s.robots.length} value={count} onChange={e=>setCount(Number(e.target.value))}/></label>}{incident==='Passage bloqué'&&<p>{cell?`Case ${cell.x+1}, ${cell.y+1} choisie`:'Cliquez sur une case libre de la carte.'}</p>}<button className="primary" onClick={perform}>Déclencher l’incident</button></div>{message&&<p role="status" className="incident-diagnosis">{message}</p>}
 {records.length>0&&<div className="incident-history" aria-label="Incidents de cette expérience">{records.map(r=><button key={r.id} aria-pressed={r.id===active} onClick={()=>setActive(r.id)}>{r.name} · {r.target} <span className={incidentResolved(engine,r)?'resolved':'active'}>{incidentResolved(engine,r)?'Résolu':'Actif'}</span></button>)}</div>}
 <div className="map-management-body"><div className="workspace-map"><Warehouse guidance={incident==='Passage bloqué'?'Cliquez sur une case libre pour placer l’obstacle':'Cliquez sur la cible de votre incident'} showLocations state={s} selected={target||null} select={select} highlighted={record?[...record.shelves,...record.walls,...record.robots]:[]} onCell={incident==='Passage bloqué'?(x,y)=>{setCell({x,y});setTarget('')}:undefined} speed={props.speed} playing={props.playing} tool="select" onPlace={()=>{}}/></div><aside className="workspace-context lab-resolution"><h2>Diagnostic et solutions</h2>{record?<><h3>{record.name} · {incidentResolved(engine,record)?'Résolu':'Actif'}</h3><p>Origine : {record.target} · pas {record.tick}</p><p>{frenchMessage(record.message)}</p><p>{affectedOrders.length} commandes touchées · {affectedRobots.length} robots concernés.</p>{affectedRobots.map(r=><div className="diagnostic-card" key={r.id}><strong>{r.code} · {robotStates[r.state]}</strong><p>{r.battery.toFixed(0)} % · {r.cargo?'colis sécurisé à bord':'sans colis'} · mission {r.orderId??'aucune'}</p><p>{r.decision?.message}</p>{robotIncident&&r.state==='fault'&&!r.disabled&&<button onClick={()=>report(engine.repairRobot(r.id))}>Réparer · {money(PRICES.repair)}</button>}{batteryIncident&&r.state!=='fault'&&!r.cargo&&!['to-charge','charging'].includes(r.state)&&<button onClick={()=>report(engine.chargeRobot(r.id))}>Recharger et libérer la mission non prélevée</button>}{batteryIncident&&r.state==='fault'&&<button onClick={()=>report(engine.repairRobot(r.id))}>Réparer · {money(PRICES.repair)}</button>}</div>)}
 {affectedOrders.map(o=><p key={o.id}>{o.id} · {o.delivered}/{o.quantity} livrées · {o.status==='completed'?'Terminée':o.blockReason??'En traitement par le moteur'} · robots : {s.robots.filter(r=>r.orderId===o.id).map(r=>r.code).join(', ')||'aucun affecté actuellement'}</p>)}
 {robotIncident&&<><p>Une mission non prélevée est libérée automatiquement. Reprenez la simulation pour qu’un autre robot compatible la récupère. Un colis à bord attend la réparation.</p>{!s.robots.some(r=>r.state!=='fault'&&!r.disabled)&&<button onClick={()=>report(engine.buyRobot())}>Acheter un robot · {money(PRICES.robot)}</button>}</>}
 {wallsIncident&&<><p>{affectedRobots.filter(r=>r.state==='blocked').length} robots bloqués actuellement. Les itinéraires sont recalculés au prochain pas ; un détour peut atténuer l’incident sans retirer l’obstacle.</p>{record.walls.filter(id=>s.tiles.some(t=>t.id===id)).map(id=><button key={id} onClick={()=>{const t=s.tiles.find(t=>t.id===id)!;report(engine.removeAt(t.x,t.y))}}>Retirer l’obstacle · {id}</button>)}<button onClick={()=>props.build('select')}>Modifier le plan</button></>}
 {stockIncident&&record.shelves.map(id=>{const t=s.tiles.find(t=>t.id===id);return t?<div className="diagnostic-card" key={id}><strong>{t.location} · {engine.stockInfo(t).available} disponibles</strong><button onClick={()=>report(engine.adjustStock(id,20))}>Réapprovisionner +20 · {money(20*PRICES.stockUnit)}</button><p>Les commandes sans source imposée utilisent aussi les autres rayonnages compatibles. Les réservations restent protégées.</p></div>:null})}
 {record.name==='Zone interdite'&&record.shelves.map(id=><button key={id} onClick={()=>report(engine.setShelfPermissions(id))}>Rouvrir les permissions de {s.tiles.find(t=>t.id===id)?.location}</button>)}
 {(stationIncident||batteryIncident)&&<><p>{s.robots.filter(r=>r.state==='waiting'||r.state==='to-charge').length} robots en attente ou en route · {s.robots.filter(r=>r.state==='charging').length} bornes occupées / {s.tiles.filter(t=>t.kind==='charger').length} installées.</p><button onClick={()=>props.build('charger')}>Ajouter une borne · {money(PRICES.charger)}</button></>}
 {record.name==='Commandes massives'&&<p>Les commandes sont traitées selon leur priorité et les ressources disponibles. Les limites de stock et d’accès restent applicables.</p>}
 <button onClick={props.toggle}>{props.playing?'Pause':'Reprendre · observer la résolution'}</button></>:<p>Déclenchez un incident pour afficher son diagnostic et ses solutions.</p>}</aside></div>
 <details className="lab-advanced"><summary>Outils de comparaison et aménagement</summary><div className="button-row"><button onClick={props.arena}>Ouvrir SWARM ARENA</button><button onClick={props.compare}>Comparer les stratégies · 10 min</button><button onClick={()=>props.build('select')}>Modifier le plan</button></div>{props.comparison}</details></section>;
}
