import {describe,it,expect} from 'vitest';
import {Engine,PRICES} from './engine';
import {parseCopilot} from './copilot';
import {prepareArena} from './arena';
import {DuelSession} from './duel';
import {triggerIncident,diagnose,INCIDENTS} from './incidents';
function empty(){const e=new Engine(42,{demo:true});e.state.orders=[];return e;}
function setup(){const e=empty(),t=e.state.tiles.find(t=>t.kind==='shelf')!,r=e.state.robots[0];expect(e.adjustStock(t.id,-t.stock!).ok).toBe(true);expect(e.createProduct('Coca-Cola','COCA',12,'#db675f').ok).toBe(true);expect(e.configureShelf(t.id,'COCA',100).ok).toBe(true);expect(e.adjustStock(t.id,10).ok).toBe(true);return {e,t,r};}
describe('warehouse management business invariants',()=>{
 it('creates custom products, stable locations, logs real stock and rejects duplicates',()=>{const {e,t}=setup();expect(e.products.find(p=>p.sku==='COCA')?.name).toBe('Coca-Cola');expect(t.location).toBe('A-1');expect(t.movements?.map(m=>m.quantity)).toEqual([10,-12]);expect(e.createProduct('Coca-Cola','OTHER').ok).toBe(false);expect(e.createProduct('Invalid','bad sku').ok).toBe(false);const restored=Engine.restore(e.serialize());expect(restored.serialize()).toBe(e.serialize());e.place('shelf',0,0);const added=e.state.tiles.at(-1)!;expect(added.stock).toBe(0);expect(new Set(e.state.tiles.filter(t=>t.kind==='shelf').map(t=>t.location)).size).toBe(41);});
 it('enforces capacity, space consumption, reserved stock and budget',()=>{const {e,t}=setup();expect(e.configureShelf(t.id,'COCA',9).ok).toBe(false);e.createOrder('COCA',2,3,{sourceId:t.id});e.tick();const info=e.stockInfo(t);expect(info.reserved).toBe(1);expect(e.adjustStock(t.id,-10).ok).toBe(false);const before=t.stock;e.state.budget=0;expect(e.adjustStock(t.id,1).ok).toBe(false);expect(t.stock).toBe(before);expect(e.removeAt(t.x,t.y).ok).toBe(false);expect(e.configureShelf(t.id,'A',500).ok).toBe(false);});
 it('exclusive and priority permissions choose actual eligible robots',()=>{const {e,t,r}=setup(),other=e.state.robots[1];expect(e.setShelfPermissions(t.id,[other.id],other.id).ok).toBe(true);expect(e.createOrder('COCA',1,2,{sourceId:t.id,robotId:r.id}).ok).toBe(false);e.createOrder('COCA',1,2,{sourceId:t.id});e.tick();expect(other.shelfId).toBe(t.id);expect(r.orderId).toBeUndefined();expect(other.decision?.message).toContain('prioritaire');});
 it('prioritizes a permitted designated robot before the strategy score',()=>{const {e,t,r}=setup();e.setShelfPermissions(t.id,undefined,r.id);e.createOrder('COCA',1,2,{sourceId:t.id});e.tick();expect(r.shelfId).toBe(t.id);expect(e.state.robots.filter(r=>r.orderId)).toHaveLength(1);});
 it('honors priority locations even when an automatic source has a nearer alternative',()=>{const e=empty(),r=e.state.robots[0],t=e.state.tiles.filter(t=>t.kind==='shelf'&&t.sku==='A').at(-1)!;e.setRobotPermissions(r.id,undefined,[t.id]);e.createOrder('A',1,2,{robotId:r.id});e.tick();expect(r.shelfId).toBe(t.id);});
 it('rejects a selected robot order larger than its authorized available stock',()=>{const {e,t,r}=setup();e.adjustStock(t.id,-8);e.setRobotPermissions(r.id,[t.id]);const other=e.state.tiles.filter(s=>s.kind==='shelf'&&s.id!==t.id)[0];e.adjustStock(other.id,-other.stock!);e.configureShelf(other.id,'COCA',100);e.adjustStock(other.id,10);expect(e.createOrder('COCA',5,2,{robotId:r.id}).ok).toBe(false);expect(e.createOrder('COCA',2,2,{robotId:r.id}).ok).toBe(true);});
 it('releases an unpicked mission after authorization is revoked, without duplication',()=>{const {e,t,r}=setup();e.setShelfPermissions(t.id,[r.id]);e.createOrder('COCA',1,3,{sourceId:t.id});e.tick();const o=e.state.orders[0];expect(o.reserved).toBe(1);e.setShelfPermissions(t.id,[]);expect(o.reserved).toBe(0);expect(r.orderId).toBeUndefined();e.tick(30);expect(o.delivered).toBe(0);expect(o.blockReason).toContain('autorisé');e.setShelfPermissions(t.id);e.tick(200);expect(o.delivered).toBe(1);expect(t.stock).toBe(9);});
 it('finishes secured cargo when permissions change during transport',()=>{const {e,t,r}=setup();e.createOrder('COCA',1,2,{sourceId:t.id,robotId:r.id});while(!r.cargo)e.tick();e.setRobotPermissions(r.id,[]);expect(r.cargo).toBe(1);e.tick(200);expect(e.state.orders[0].status).toBe('completed');expect(t.stock).toBe(9);});
 it('delivers five units with the chosen robot, source and depot, charging income once',()=>{const {e,t,r}=setup(),depot=e.state.tiles.find(t=>t.kind==='depot')!;e.createOrder('COCA',5,3,{sourceId:t.id,robotId:r.id,depotId:depot.id});const budget=e.state.budget;e.tick(600);const o=e.state.orders[0];expect(o.delivered).toBe(5);expect(o.reserved).toBe(0);expect(o.income).toBe(60);expect(e.state.revenue).toBe(60);expect(t.stock).toBe(5);expect(o.assignments).toHaveLength(5);expect(o.assignments?.every(a=>a.robotId===r.id)).toBe(true);expect(t.movements?.filter(m=>m.reason==='Prélèvement')).toHaveLength(5);expect(e.state.budget).toBeLessThan(budget+60);e.tick(200);expect(e.state.revenue).toBe(60);});
 it('checks exact sources, selected robots and protected cancellations',()=>{const {e,t,r}=setup();expect(e.createOrder('COCA',11,2,{sourceId:t.id}).ok).toBe(false);expect(e.createOrder('COCA',1,2,{sourceId:'bad'}).ok).toBe(false);expect(e.createOrder('COCA',1,2,{depotId:'bad'}).ok).toBe(false);e.createOrder('COCA',1,2,{sourceId:t.id,robotId:r.id});e.tick();expect(e.cancelOrder(e.state.orders[0].id).ok).toBe(true);expect(e.stockInfo(t).reserved).toBe(0);e.createOrder('COCA',1,2,{robotId:r.id});while(!r.cargo)e.tick();expect(e.cancelOrder(e.state.orders[0].id).ok).toBe(false);});
 it('diagnoses and repairs failures, keeps cargo and charges configured costs exactly',()=>{const {e,t,r}=setup();e.createOrder('COCA',1,2,{robotId:r.id});while(!r.cargo)e.tick();const id=r.orderId;e.faultRobot(r.id);expect(diagnose(e).orders.map(o=>o.id)).toContain(id);const before=e.state.budget;e.state.budget=0;expect(e.repairRobot(r.id).ok).toBe(false);expect(r.cargo).toBe(1);e.state.budget=before;expect(e.repairRobot(r.id).ok).toBe(true);expect(e.state.budget).toBe(before-PRICES.repair);e.tick(200);expect(e.state.orders[0].delivered).toBe(1);expect(t.stock).toBe(9);});
 it('supports administrative service suspension without repair fees or mission loss',()=>{const {e,r}=setup();e.createOrder('COCA',1,2,{robotId:r.id});e.tick();e.setService(r.id,true);expect(r.disabled).toBe(true);expect(r.orderId).toBeUndefined();expect(e.eligibleRobots('COCA').some(robot=>robot.id===r.id)).toBe(false);e.setService(r.id,false);expect(r.disabled).toBe(false);expect(r.state).toBe('idle');});
 it('cannot bypass a paid repair by suspending a failed robot',()=>{const {e,r}=setup();e.faultRobot(r.id);expect(e.setService(r.id,true).ok).toBe(false);expect(e.setService(r.id,false).ok).toBe(false);expect(r.state).toBe('fault');expect(e.repairRobot(r.id).ok).toBe(true);});
 it('cleans deleted references while retaining stable historical codes',()=>{const {e,r,t}=setup();e.setShelfPermissions(t.id,[r.id],r.id);e.removeRobot(r.id);expect(t.allowedRobots).toEqual([]);expect(t.priorityRobot).toBeUndefined();e.buyRobot();expect(e.state.robots.at(-1)?.code).toBe('R007');expect(()=>Engine.restore(e.serialize())).not.toThrow();});
 it('migrates legacy saves and rejects damaged catalogue and management reservations',()=>{const e=new Engine(42,{demo:true});const old=JSON.parse(e.serialize());delete old.robotCodeCounter;delete old.products;delete old.managementVersion;delete old.locationCounter;old.tiles.forEach((t:Record<string,unknown>)=>{delete t.location;delete t.capacity;delete t.movements});old.robots.forEach((r:Record<string,unknown>)=>delete r.code);const migrated=Engine.restore(JSON.stringify(old));expect(migrated.products).toHaveLength(3);expect(migrated.state.tiles[0].location).toBe('A-1');expect(migrated.state.robots[0].code).toBe('R001');const corrupt=JSON.parse(e.serialize());corrupt.products[0].value=-1;expect(()=>Engine.restore(JSON.stringify(corrupt))).toThrow();const permissions=JSON.parse(e.serialize());permissions.tiles[0].allowedRobots=['nonexistent'];expect(()=>Engine.restore(JSON.stringify(permissions))).toThrow();});
});
describe('local Copilot intents and safe confirmation',()=>{
 it('parses all presentation stock, permissions, question and multi-unit order examples',()=>{const {e,t}=setup();const requests=['Crée un produit Fanta.','Mets R001 prioritaire sur A-1.','Seul R001 peut travailler sur A-1.','Ajoute 2 Coca-Cola dans A-1.','Crée une commande urgente de 5 Coca-Cola avec R001.'];for(const request of requests){const before=e.serialize(),plan=parseCopilot(e,request);expect(plan.mutates).toBe(true);expect(e.serialize()).toBe(before);expect(plan.execute?.().ok).toBe(true);}expect(t.stock).toBe(12);expect(parseCopilot(e,'Combien de Coca-Cola reste-t-il ?').message).toContain('12 disponibles');expect(parseCopilot(e,'Montre les emplacements presque vides.').mutates).toBe(false);});
 it('does not execute unknown or ambiguous instructions and checks current constraints',()=>{const {e,t}=setup();const before=e.serialize();for(const input of ['mets des trucs là','ajoute dix Coca-Cola dans A-1','supprime tous les robots','Crée une commande de 99 Coca-Cola','Ajoute 10 Fanta dans A-1']){expect(parseCopilot(e,input).mutates).toBe(false);expect(e.serialize()).toBe(before);}const plan=parseCopilot(e,'Ajoute 2 Coca-Cola dans A-1');e.state.budget=0;expect(plan.execute?.().ok).toBe(false);expect(t.stock).toBe(10);});
});
describe('configured arena and real incident laboratory',()=>{
 it('prepares exactly 50 deterministic orders, equal clones and immutable live state',()=>{const e=new Engine(42,{demo:true}),before=e.serialize(),a=prepareArena(before,'2026',50),b=prepareArena(before,'2026',50);expect(a.snapshot).toBe(b.snapshot);expect(Engine.restore(a.snapshot).state.orders.filter(o=>o.status!=='completed')).toHaveLength(50);const duel=new DuelSession(a.snapshot,240);duel.tick(240);const results=[duel.nearest.serialize(),duel.balanced.serialize()];duel.reset();duel.tick(240);expect([duel.nearest.serialize(),duel.balanced.serialize()]).toEqual(results);expect(e.serialize()).toBe(before);expect(()=>prepareArena(before,'2026',201)).toThrow();});
 it('discloses limited stock and protects active orders when reducing the workload',()=>{const e=empty();e.state.tiles.filter(t=>t.kind==='shelf').forEach(t=>t.stock=0);const prepared=prepareArena(e.serialize(),'current',50);expect(prepared.warning).toContain('Stock limité');const active=new Engine(42,{demo:true});active.tick();expect(()=>prepareArena(active.serialize(),'current',10)).toThrow('missions actives');});
 it('uses energy only as the third transparent winner criterion',()=>{const duel=new DuelSession(empty().serialize(),20);duel.nearest.state.energy+=2;expect(duel.winner).toBe('balanced');duel.balanced.state.energy+=2;expect(duel.winner).toBe('tie');});
 it('all ten incident scenarios change real state or explain why unavailable',()=>{for(const name of INCIDENTS){const e=new Engine(42,{demo:true});e.tick(2);const before=e.serialize(),result=triggerIncident(e,name,undefined,3);if(result.ok)expect(e.serialize()).not.toBe(before);else expect(result.message.length).toBeGreaterThan(5);expect(()=>Engine.restore(e.serialize())).not.toThrow();}});
 it('restores a laboratory baseline exactly without changing external saved state',()=>{const e=new Engine(42,{demo:true});e.tick(12);const baseline=e.serialize();triggerIncident(e,'Pannes simultanées',undefined,4);expect(e.state.robots.filter(r=>r.state==='fault')).toHaveLength(4);const restored=Engine.restore(baseline);expect(restored.serialize()).toBe(baseline);});
});
