import {describe,it,expect} from 'vitest';
import {Engine,PRICES} from './engine';
import {planSupply} from './supply';
import {stockOperation,saveShelfParameters} from './operations';
import {parseCopilot} from './copilot';
import {MAX_STOCK,MAX_ORDER} from './limits';
const rack=(e:Engine,location:string)=>e.state.tiles.find(t=>t.location===location)!;
function setup(){const e=new Engine();e.createProduct('Coca-Cola','COCA',12);return e;}
describe('empty normal warehouse and compatible saves',()=>{
 it('starts with zero orders, revenue, cargo and stock; idle robots retain their initial batteries',()=>{const e=new Engine();expect(e.state.orders).toEqual([]);expect(e.metrics.completed).toBe(0);expect(e.state.revenue).toBe(0);expect(e.state.costs).toBe(0);expect(e.state.robots.map(r=>r.battery)).toEqual([95,89,83,77,71,65]);expect(e.state.robots.every(r=>r.state==='idle'&&!r.orderId&&!r.cargo)).toBe(true);expect(e.state.tiles.filter(t=>t.kind==='shelf').every(t=>t.stock===0&&t.capacity===null)).toBe(true);e.tick(100);expect(e.state.orders).toEqual([]);expect(e.state.revenue).toBe(0);expect(e.state.robots.every(r=>r.state==='idle')).toBe(true);});
 it('keeps explicit demos and restores old orders, finite capacities and in-flight cargo without resetting them',()=>{const demo=new Engine(42,{demo:true});expect(demo.state.orders).toHaveLength(12);expect(rack(demo,'A-1').stock).toBe(12);expect(rack(demo,'A-1').capacity).toBe(500);for(let i=0;i<100&&!demo.state.robots.some(r=>r.cargo);i++)demo.tick();const raw=JSON.parse(demo.serialize());delete raw.supplyMode;delete raw.subsidizedSupply;const restored=Engine.restore(JSON.stringify(raw));expect(restored.serialize()).toBe(JSON.stringify(raw));expect(restored.state.robots.some(r=>r.cargo)).toBe(true);expect(restored.state.orders.length).toBe(12);});
 it('creates a product with zero stock and a normal reset never recreates demo orders',()=>{const e=setup();expect(e.products.some(p=>p.sku==='COCA')).toBe(true);expect(e.state.tiles.filter(t=>t.sku==='COCA').reduce((n,t)=>n+(t.stock??0),0)).toBe(0);const fresh=new Engine(e.state.seed);expect(fresh.state.orders).toHaveLength(0);expect(fresh.state.revenue).toBe(0);});
});
describe('shared supply planning and exact quantities',()=>{
 it('places 100 automatically in A-1 and 50 manually, with exact cost and no orders created',()=>{const e=setup(),before=e.serialize(),plan=planSupply(e,'COCA',100);expect(plan.placements).toEqual([{id:rack(e,'A-1').id,location:'A-1',quantity:100}]);expect(e.serialize()).toBe(before);const budget=e.state.budget;expect(stockOperation(e,'COCA','Coca-Cola',100).ok).toBe(true);expect(stockOperation(e,'COCA','Coca-Cola',50,rack(e,'A-1').id).ok).toBe(true);expect(rack(e,'A-1').stock).toBe(150);expect(e.state.budget).toBe(budget-150*PRICES.stockUnit);expect(e.state.orders).toHaveLength(0);});
 it('registers only shelf parameters, even when a quantity field has been edited elsewhere',()=>{const e=setup();stockOperation(e,'COCA','Coca-Cola',100);const budget=e.state.budget;expect(saveShelfParameters(e,rack(e,'A-1').id,'COCA',null,undefined,e.state.robots[0].id).ok).toBe(true);expect(rack(e,'A-1').stock).toBe(100);expect(e.state.budget).toBe(budget);});
 it('accepts 1000 then 10000 and even the numeric safety maximum without multiplying entities',()=>{const e=setup();e.setSupplyMode(true);const entities=e.state.tiles.length,robots=e.state.robots.length;expect(stockOperation(e,'COCA','Coca-Cola',1000).ok).toBe(true);expect(stockOperation(e,'COCA','Coca-Cola',10000).ok).toBe(true);expect(rack(e,'A-1').stock).toBe(11000);expect(e.state.orders).toHaveLength(0);expect(e.state.tiles).toHaveLength(entities);expect(e.state.robots).toHaveLength(robots);expect(e.adjustStock(rack(e,'A-1').id,MAX_STOCK-11000).ok).toBe(true);expect(rack(e,'A-1').stock).toBe(MAX_STOCK);expect(e.adjustStock(rack(e,'A-1').id,1).ok).toBe(false);expect(rack(e,'A-1').stock).toBe(MAX_STOCK);expect(()=>Engine.restore(e.serialize())).not.toThrow();});
 it('distributes an addition across configured capacities and reports every exact placement',()=>{const e=setup();e.setSupplyMode(true);e.configureShelf(rack(e,'A-1').id,'COCA',60);e.configureShelf(rack(e,'A-2').id,'COCA',60);e.adjustStock(rack(e,'A-1').id,10);e.adjustStock(rack(e,'A-2').id,10);const plan=planSupply(e,'COCA',100);expect(plan.placements.map(t=>[t.location,t.quantity])).toEqual([['A-1',50],['A-2',50]]);const result=stockOperation(e,'COCA','Coca-Cola',100);expect(result.ok).toBe(true);expect(result.message).toContain('A-1 : 50');expect(result.message).toContain('A-2 : 50');expect(rack(e,'A-1').stock).toBe(60);expect(rack(e,'A-2').stock).toBe(60);});
 it('respects space consumption and preserves a finite capacity unless explicitly changed',()=>{const e=new Engine();e.createProduct('Cartons','BOX',10,'#123456',5);e.configureShelf(rack(e,'A-1').id,'BOX',100);e.setSupplyMode(true);expect(e.adjustStock(rack(e,'A-1').id,20).ok).toBe(true);expect(planSupply(e,'BOX',1,rack(e,'A-1').id).ok).toBe(false);expect(e.configureShelf(rack(e,'A-1').id,'BOX',10000).ok).toBe(true);expect(e.adjustStock(rack(e,'A-1').id,1000).ok).toBe(true);expect(rack(e,'A-1').stock).toBe(1020);});
 it('skips forbidden automatic locations and fails atomically when all locations are incompatible',()=>{const e=setup();e.setShelfPermissions(rack(e,'A-1').id,[]);expect(planSupply(e,'COCA',100).placements[0].location).toBe('A-2');for(const t of e.state.tiles.filter(t=>t.kind==='shelf'))e.setShelfPermissions(t.id,[]);const before=e.serialize();expect(stockOperation(e,'COCA','Coca-Cola',100).ok).toBe(false);expect(e.serialize()).toBe(before);});
 it('never replaces occupied goods and rejects invalid, negative, decimal and excessive numbers',()=>{const e=setup();stockOperation(e,'COCA','Coca-Cola',100);e.createProduct('Fanta','FANTA');const before=e.serialize();expect(stockOperation(e,'FANTA','Fanta',50,rack(e,'A-1').id).ok).toBe(false);for(const quantity of [0,-10,1.5,NaN,Infinity,MAX_STOCK+1,Number.MAX_SAFE_INTEGER]){expect(planSupply(e,'COCA',quantity).ok).toBe(false);expect(stockOperation(e,'COCA','Coca-Cola',quantity).ok).toBe(false);}expect(e.serialize()).toBe(before);});
 it('creates and stocks a new product atomically, rejecting collisions and failure without a phantom product',()=>{const e=new Engine();e.setSupplyMode(true);const draft={sku:'EAU',name:'Eau',value:1,color:'#1267ab',size:1};expect(stockOperation(e,'EAU','Eau',1000,undefined,true,draft).ok).toBe(true);expect(e.products.find(p=>p.sku==='EAU')).toEqual(draft);expect(rack(e,'A-1').stock).toBe(1000);const before=e.serialize();expect(stockOperation(e,'EAU','Autre eau',10,undefined,false,{...draft,name:'Autre eau'}).ok).toBe(false);expect(e.serialize()).toBe(before);e.setSupplyMode(false);e.state.budget=0;const snapshot=e.serialize();expect(stockOperation(e,'FANTA','Fanta',100).ok).toBe(false);expect(e.serialize()).toBe(snapshot);expect(e.products.some(p=>p.sku==='FANTA')).toBe(false);});
});
describe('economy mode and real order validation',()=>{
 it('makes only supply free, tracks waived cost, persists the mode and works with a negative operating balance',()=>{const e=setup();e.state.budget=-20;e.setSupplyMode(true);expect(stockOperation(e,'COCA','Coca-Cola',11000).ok).toBe(true);expect(e.state.budget).toBe(-20);expect(e.state.costs).toBe(0);expect(e.state.subsidizedSupply).toBe(88000);expect(e.buyRobot().ok).toBe(false);expect(e.place('charger',0,0).ok).toBe(false);const restored=Engine.restore(e.serialize());expect(restored.state.supplyMode).toBe('free');expect(restored.state.subsidizedSupply).toBe(88000);e.setSupplyMode(false);expect(e.adjustStock(rack(e,'A-1').id,1).ok).toBe(false);expect(rack(e,'A-1').stock).toBe(11000);});
 it('accepts a 100-unit order from split stock and delivers every unit progressively without expanding the order list',()=>{const e=setup();e.setSupplyMode(true);stockOperation(e,'COCA','Coca-Cola',50,rack(e,'A-1').id);stockOperation(e,'COCA','Coca-Cola',50,rack(e,'A-2').id);expect(e.createOrder('COCA',100).ok).toBe(true);expect(e.state.orders).toHaveLength(1);for(let i=0;i<8&&e.state.orders[0].status!=='completed';i++)e.tick(1000);const o=e.state.orders[0];expect(o.status).toBe('completed');expect(o.delivered).toBe(100);expect(o.reserved).toBe(0);expect(o.income).toBe(1200);expect(rack(e,'A-1').stock!+rack(e,'A-2').stock!).toBe(0);expect(e.state.robots.every(r=>r.cargo===0)).toBe(true);const revenue=e.state.revenue;e.tick(100);expect(e.state.revenue).toBe(revenue);expect(()=>Engine.restore(e.serialize())).not.toThrow();});
 it('delivers ten automatically, then honors a manually chosen robot for another real order',()=>{const e=setup();stockOperation(e,'COCA','Coca-Cola',150);e.createOrder('COCA',10);e.tick(1000);expect(e.state.orders[0].status).toBe('completed');expect(rack(e,'A-1').stock).toBe(140);const r=e.state.robots[0];e.setRobotProductPermissions(r.id,['COCA']);expect(e.createOrder('COCA',5,2,{robotId:r.id}).ok).toBe(true);e.tick(1000);expect(e.state.orders[1].status).toBe('completed');expect(e.state.orders[1].assignments?.every(a=>a.robotId===r.id)).toBe(true);expect(rack(e,'A-1').stock).toBe(135);});
 it('explains insufficient stock and robot permissions without mutating readonly validation',()=>{const e=setup();stockOperation(e,'COCA','Coca-Cola',20);const r=e.state.robots[0];e.setRobotProductPermissions(r.id,['A']);const before=e.serialize();expect(e.orderValidation('COCA',100).message).toContain('20 Coca-Cola disponibles pour 100');expect(e.orderValidation('COCA',10,2,{robotId:r.id,sourceId:rack(e,'A-1').id}).message).toContain('R001 n’a pas accès');expect(e.orderValidation('COCA',-1).ok).toBe(false);expect(e.orderValidation('COCA',NaN).ok).toBe(false);expect(e.orderValidation('COCA',MAX_ORDER+1).ok).toBe(false);expect(e.serialize()).toBe(before);expect(e.createOrder('COCA',100).ok).toBe(false);expect(e.state.orders).toHaveLength(0);});
 it('rejects missing or sealed depots, unreachable stock and depleted compatible batteries',()=>{const e=setup();stockOperation(e,'COCA','Coca-Cola',100);for(const r of e.state.robots)r.battery=10;expect(e.orderValidation('COCA',10).message).toContain('Autonomie insuffisante');for(const r of e.state.robots)r.battery=95;e.state.tiles=e.state.tiles.filter(t=>t.kind!=='depot');expect(e.orderValidation('COCA',10).message).toContain('Aucun dépôt accessible');const sealed=setup();stockOperation(sealed,'COCA','Coca-Cola',100);for(let y=0;y<16;y++)sealed.place('wall',4,y);expect(sealed.orderValidation('COCA',10).ok).toBe(false);expect(sealed.state.orders).toHaveLength(0);});
 it('preserves reservations, cargo, completed orders and restrictions through a large-stock save',()=>{const e=setup();e.setSupplyMode(true);stockOperation(e,'COCA','Coca-Cola',11000);e.setRobotProductPermissions(e.state.robots[0].id,['COCA']);e.createOrder('COCA',10);for(let i=0;i<100&&!e.state.robots.some(r=>r.cargo);i++)e.tick();const snapshot=e.serialize(),restored=Engine.restore(snapshot);expect(restored.serialize()).toBe(snapshot);expect(restored.state.robots.some(r=>r.cargo)).toBe(true);expect(restored.state.robots[0].allowedProducts).toEqual(['COCA']);restored.tick(1000);expect(restored.state.orders[0].status).toBe('completed');expect(rack(restored,'A-1').stock).toBe(10990);const corrupt=JSON.parse(snapshot);corrupt.tiles.find((t:{location:string})=>t.location==='A-1').stock=Number.MAX_SAFE_INTEGER;expect(()=>Engine.restore(JSON.stringify(corrupt))).toThrow();});
});
describe('Copilot uses the same large-quantity supply services',()=>{
 it('handles grouped thousands, free shelves, real positions, queries and concrete orders',()=>{const e=setup();e.setSupplyMode(true);for(const text of ['Ajoute 100 Coca-Cola.','Crée Eau et ajoute 1 000 unités dans un rayonnage libre.']){const before=e.serialize(),plan=parseCopilot(e,text);expect(plan.mutates,plan.message).toBe(true);expect(e.serialize()).toBe(before);expect(plan.execute?.().ok).toBe(true);}expect(rack(e,'A-1').stock).toBe(100);expect(rack(e,'A-2').stock).toBe(1000);expect(parseCopilot(e,'Où se trouve mon Coca-Cola ?').message).toContain('A-1');expect(parseCopilot(e,'Combien de Coca-Cola reste-t-il ?').message).toContain('100 disponibles');const plan=parseCopilot(e,'Crée une commande de 20 Coca-Cola.');expect(plan.execute?.().ok).toBe(true);expect(e.state.orders[0].quantity).toBe(20);});
 it('reports exact split placement and an actual failure when the confirmation becomes incompatible',()=>{const e=setup();e.setSupplyMode(true);e.configureShelf(rack(e,'A-1').id,'COCA',50);e.configureShelf(rack(e,'A-2').id,'COCA',50);e.adjustStock(rack(e,'A-1').id,10);e.adjustStock(rack(e,'A-2').id,10);const plan=parseCopilot(e,'Ajoute 80 Coca-Cola.');expect(plan.targetIds).toEqual([rack(e,'A-1').id,rack(e,'A-2').id]);expect(plan.execute?.().message).toContain('A-2 : 40');const pending=parseCopilot(e,'Mets 10 Coca-Cola dans A-3.');e.createProduct('Fanta','FANTA');stockOperation(e,'FANTA','Fanta',10,rack(e,'A-3').id);const before=e.serialize();expect(pending.execute?.().ok).toBe(false);expect(e.serialize()).toBe(before);});
});
