import {useState} from 'react';
import type {Engine,Result,Product} from './engine';
import Warehouse from './Warehouse';
import {planSupply,productReference} from './supply';
import {stockOperation} from './operations';
import {MAX_STOCK} from './limits';
import {money} from './presentation';
type Props={engine:Engine;initialSku?:string;initialQuantity?:number;playing:boolean;speed:number;cancel:()=>void;applied:(r:Result,ids:string[])=>void;build?:()=>void};
export default function SupplyForm({engine,initialSku,initialQuantity,playing,speed,cancel,applied,build}:Props){
 const [selectedSku,setSelectedSku]=useState(initialSku??engine.products[0]?.sku??'__new__'),[quantity,setQuantity]=useState(initialQuantity??100),[mode,setMode]=useState('auto'),[target,setTarget]=useState('');
 const [name,setName]=useState(''),[sku,setSku]=useState(''),[value,setValue]=useState(85),[color,setColor]=useState('#75d7e5'),[size,setSize]=useState(1);
 const newProduct=selectedSku==='__new__',actualSku=newProduct?sku:selectedSku,draft:Product|undefined=newProduct?{name,sku,value,color,size}:undefined;
 const plan=mode==='manual'&&!target?{ok:false,message:'Cliquez sur un rayonnage de la carte pour choisir l’emplacement.',placements:[],cost:0}:planSupply(engine,actualSku,quantity,mode==='manual'?target:undefined,false,draft);
 const selected=engine.state.tiles.find(t=>t.id===target),cost=Number.isSafeInteger(quantity)&&quantity>0?engine.supplyCost(quantity):0;
 return <><div className="supply-heading"><div><h2>Ajouter du stock</h2><p>Approvisionnez un produit. Les robots ne livrent qu’après la création d’une commande.</p></div><button onClick={cancel}>Annuler l’approvisionnement</button></div><div className="map-management-body supply-workspace"><div className="workspace-map"><Warehouse showLocations guidance={mode==='manual'?'Cliquez sur le rayonnage où ajouter les marchandises':'Les emplacements retenus sont indiqués sur la carte'} state={engine.state} selected={mode==='manual'?target||null:null} select={id=>{if(engine.state.tiles.some(t=>t.kind==='shelf'&&t.id===id)){setMode('manual');setTarget(id!)}}} highlighted={plan.placements.map(t=>t.id)} playing={playing} speed={speed} tool="select" onPlace={()=>{}}/></div><aside className="workspace-context"><form onSubmit={event=>{event.preventDefault();if(!plan.ok)return;const fresh=planSupply(engine,actualSku,quantity,mode==='manual'?target:undefined,false,draft);if(!fresh.ok){applied(fresh,[]);return}const r=stockOperation(engine,actualSku,draft?.name??engine.products.find(p=>p.sku===actualSku)?.name??actualSku,quantity,mode==='manual'?target:undefined,false,draft);applied(r,r.ok?fresh.placements.map(t=>t.id):[])}}>
 <label>Produit à approvisionner<select value={selectedSku} onChange={e=>setSelectedSku(e.target.value)}>{engine.products.map(p=><option key={p.sku} value={p.sku}>{p.name}</option>)}<option value="__new__">+ Créer un nouveau produit</option></select></label>
 {newProduct&&<fieldset className="new-product-fields"><legend>Nouveau produit</legend><label>Nom du nouveau produit<input maxLength={60} value={name} onChange={e=>{setName(e.target.value);setSku(productReference(e.target.value))}}/></label><label>SKU du nouveau produit<input maxLength={24} value={sku} onChange={e=>setSku(e.target.value.toUpperCase())}/></label><details><summary>Valeur, couleur et encombrement</summary><label>Valeur du nouveau produit<input type="number" min="0" max="100000" value={value} onChange={e=>setValue(Number(e.target.value))}/></label><label>Couleur du nouveau produit<input type="color" value={color} onChange={e=>setColor(e.target.value)}/></label><label>Encombrement du nouveau produit<input type="number" min="1" max="10" value={size} onChange={e=>setSize(Number(e.target.value))}/></label></details></fieldset>}
 <label>Quantité à approvisionner<input type="number" min="1" max={MAX_STOCK} step="1" value={Number.isNaN(quantity)?'':quantity} onChange={e=>setQuantity(e.target.value===''?NaN:Number(e.target.value))}/></label><label>Placement du stock<select value={mode} onChange={e=>setMode(e.target.value)}><option value="auto">Automatique</option><option value="manual">Manuel · choisir sur la carte</option></select></label>
 {mode==='manual'&&<><p>Rayonnage sélectionné : <strong>{selected?.location??'aucun'}</strong></p><details><summary>Choisir un rayonnage dans la liste</summary><label>Emplacement manuel<select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Choisir</option>{engine.state.tiles.filter(t=>t.kind==='shelf').map(t=><option key={t.id} value={t.id}>{t.location} · {engine.products.find(p=>p.sku===t.sku)?.name} · {t.stock} unités</option>)}</select></label></details></>}
 <div className="supply-preview"><strong>{engine.state.supplyMode==='free'?'Sandbox · approvisionnement gratuit':`Coût d’approvisionnement : ${money(cost)}`}</strong>{plan.ok?<><p>Emplacement{plan.placements.length>1?'s':''} retenu{plan.placements.length>1?'s':''} :</p><ul>{plan.placements.map(t=><li key={t.id}>{t.location} · {t.quantity.toLocaleString('fr-FR')} unités</li>)}</ul></>:<p role="alert">{plan.message}</p>}</div><button className="primary full" type="submit" disabled={!plan.ok}>{newProduct?'Créer le produit et ajouter du stock':'Confirmer l’ajout de stock'}</button>{!plan.ok&&build&&<button type="button" className="full" onClick={build}>Créer un rayonnage dans l’éditeur</button>}<p className="hint">Même produit d’abord, puis emplacements vides par référence. Les quantités et les permissions sont revérifiées à la confirmation. Aucune commande n’est créée.</p></form></aside></div></>;
}
