import {describe,it,expect} from 'vitest';
import {Engine,PRICES} from './engine';
import {parseCopilot} from './copilot';
import {stockOperation,saveShelf} from './operations';
import {applyLabIncident,incidentResolved} from './labSession';
import type {LabIncident} from './labSession';
function setup(){const e=new Engine(42,{demo:true});e.state.orders=[];e.createProduct('Coca-Cola','COCA',12);e.createProduct('Fanta','FANTA',10);for(const t of e.state.tiles.filter(t=>['A-1','A-2','A-4'].includes(t.location??'')))e.adjustStock(t.id,-(t.stock??0));return e;}
const shelf=(e:Engine,location:string)=>e.state.tiles.find(t=>t.location===location)!;
function execute(e:Engine,text:string){const before=e.serialize(),plan=parseCopilot(e,text);expect(e.serialize()).toBe(before);expect(plan.mutates,plan.message).toBe(true);expect(plan.execute?.().ok,plan.message).toBe(true);return plan;}
describe('map-first shared business operations',()=>{
 it('saves product, stock, capacity and priority atomically, logging a real movement',()=>{const e=setup(),t=shelf(e,'A-1'),r=e.state.robots[0],budget=e.state.budget;expect(saveShelf(e,t.id,'COCA',20,10,undefined,r.id).ok).toBe(true);expect(t.stock).toBe(10);expect(t.priorityRobot).toBe(r.id);expect(e.state.budget).toBe(budget-10*PRICES.stockUnit);expect(t.movements?.[0]?.quantity).toBe(10);expect(()=>Engine.restore(e.serialize())).not.toThrow();});
 it('rolls back all fields and product creation after budget, capacity or overwrite failure',()=>{const e=setup(),t=shelf(e,'A-1');e.state.budget=0;const before=e.serialize();expect(saveShelf(e,t.id,'COCA',20,10).ok).toBe(false);expect(e.serialize()).toBe(before);expect(stockOperation(e,'EAU','Eau',15,t.id).ok).toBe(false);expect(e.serialize()).toBe(before);e.state.budget=10000;expect(stockOperation(e,'COCA','Coca-Cola',10,t.id).ok).toBe(true);const stocked=e.serialize();expect(saveShelf(e,t.id,'FANTA',20,5).ok).toBe(false);expect(saveShelf(e,t.id,'COCA',20,-1).ok).toBe(false);expect(saveShelf(e,t.id,'COCA',5,0).ok).toBe(false);expect(e.serialize()).toBe(stocked);});
 it('chooses same-product capacity first, then the first compatible empty location deterministically',()=>{const e=setup();execute(e,'Ajoute-moi un stock de 10 Coca-Cola.');expect(shelf(e,'A-1').stock).toBe(10);execute(e,'Ajoute 10 Coca-Cola.');expect(shelf(e,'A-1').stock).toBe(20);e.configureShelf(shelf(e,'A-1').id,'COCA',20);execute(e,'Ajoute 5 Coca-Cola.');expect(shelf(e,'A-2').stock).toBe(5);execute(e,'Ajoute 5 Fanta dans un emplacement libre.');expect(shelf(e,'A-4').sku).toBe('FANTA');});
 it('creates and stocks a new product together and focuses the real selected shelf',()=>{const e=setup(),plan=execute(e,'Crée Eau et ajoute 15 unités dans A-4.');expect(plan.targetIds).toEqual([shelf(e,'A-4').id]);expect(shelf(e,'A-4').stock).toBe(15);expect(e.products.some(p=>p.name.toLowerCase()==='eau')).toBe(true);});
 it('does nothing when no compatible shelf exists or a pending action becomes impossible',()=>{const e=new Engine(42,{demo:true});const before=e.serialize(),plan=parseCopilot(e,'Ajoute 10 Fanta');expect(plan.kind).toBe('impossible');expect(e.serialize()).toBe(before);const ready=setup(),pending=parseCopilot(ready,'Mets 10 Coca-Cola dans A-1');ready.state.budget=0;const changed=ready.serialize();expect(pending.execute?.().ok).toBe(false);expect(ready.serialize()).toBe(changed);});
 it('returns true locations, quantities, low-stock shelves and no arbitrary mission for ambiguity',()=>{const e=setup();execute(e,'Mets 10 Coca-Cola dans A-1');expect(parseCopilot(e,'Dans quelle case se trouve le Coca-Cola ?').targetIds).toEqual([shelf(e,'A-1').id]);expect(parseCopilot(e,'Combien de Coca-Cola reste-t-il ?').message).toContain('10 disponibles');expect(parseCopilot(e,'Montre-moi les rayonnages presque vides.').targetIds).toContain(shelf(e,'A-2').id);const before=e.serialize();expect(parseCopilot(e,'Envoie R001').mutates).toBe(false);expect(e.serialize()).toBe(before);});
});
describe('product and location permission intersections',()=>{
 it('accepts natural robot aliases, sets product restrictions and preserves them in saves',()=>{const e=setup(),r=e.state.robots[0];execute(e,'Le robot 1 peut chercher uniquement du Coca-Cola.');expect(r.allowedProducts).toEqual(['COCA']);expect(e.state.orders).toHaveLength(0);expect(Engine.restore(e.serialize()).state.robots[0].allowedProducts).toEqual(['COCA']);execute(e,'R001 peut récupérer tous les produits.');expect(r.allowedProducts).toBeUndefined();expect(r.allowedLocations).toBeUndefined();});
 it('stock and robot conversations read the same state and honor shelf permissions',()=>{const e=setup(),r=e.state.robots[0],t=shelf(e,'A-1');execute(e,'Mets 10 Coca-Cola dans A-1');execute(e,'R001 uniquement Coca-Cola');e.setShelfPermissions(t.id,[r.id]);const answer=parseCopilot(e,'Quels robots peuvent récupérer le Coca-Cola de A-1 ?');expect(answer.message).toContain('R001');expect(answer.message).not.toContain('R002');execute(e,'Interdis R001 sur A-1');expect(parseCopilot(e,'Quel robot peut récupérer du Coca-Cola ?').message).toContain('Aucun robot autorisé');});
 it('restricts zones and authorizes an extra shelf without discarding other limits',()=>{const e=setup(),r=e.state.robots[2];execute(e,'R003 travaille seulement sur A-1 et A-2.');expect(r.allowedLocations).toEqual([shelf(e,'A-1').id,shelf(e,'A-2').id]);expect(e.isAuthorized(r,shelf(e,'B-1'))).toBe(false);execute(e,'Autorise R003 sur A-4');expect(r.allowedLocations).toContain(shelf(e,'A-4').id);});
 it('dispatch never gives a forbidden product to R001 and delivers with a compatible robot',()=>{const e=setup(),t=shelf(e,'A-2'),r=e.state.robots[0];stockOperation(e,'FANTA','Fanta',5,t.id);e.setRobotProductPermissions(r.id,['COCA']);expect(e.createOrder('FANTA',2,3,{sourceId:t.id}).ok).toBe(true);for(let i=0;i<400;i++)e.tick();const order=e.state.orders[0];expect(order.status).toBe('completed');expect(order.assignments?.some(a=>a.robotId===r.id)).toBe(false);expect(t.stock).toBe(3);});
 it('releases an unpicked disallowed mission but preserves secured cargo',()=>{const e=setup(),r=e.state.robots[0],t=shelf(e,'A-1');stockOperation(e,'COCA','Coca-Cola',5,t.id);e.createOrder('COCA',2,3,{robotId:r.id,sourceId:t.id});e.tick();expect(r.orderId).toBeDefined();e.setRobotProductPermissions(r.id,['FANTA']);expect(r.orderId).toBeUndefined();expect(e.state.orders[0].reserved).toBe(0);e.setRobotProductPermissions(r.id,['COCA']);for(let i=0;i<100&&!r.cargo;i++)e.tick();expect(r.cargo).toBe(1);e.setRobotProductPermissions(r.id,['FANTA']);expect(r.cargo).toBe(1);for(let i=0;i<100&&r.cargo;i++)e.tick();expect(e.state.orders[0].delivered).toBe(1);expect(()=>Engine.restore(e.serialize())).not.toThrow();});
 it('rejects a concrete mission with insufficient battery or inaccessible product/depot',()=>{const e=setup(),r=e.state.robots[0],t=shelf(e,'A-1');stockOperation(e,'COCA','Coca-Cola',10,t.id);r.battery=10;expect(parseCopilot(e,'Envoie R001 chercher 5 Coca-Cola').kind).toBe('impossible');r.battery=100;e.state.tiles=e.state.tiles.filter(t=>t.kind!=='depot');expect(parseCopilot(e,'Envoie R001 chercher 5 Coca-Cola').kind).toBe('impossible');expect(e.state.orders).toHaveLength(0);});
 it('creates a true urgent source-specific order and migrates optional product rules',()=>{const e=setup();stockOperation(e,'COCA','Coca-Cola',10,shelf(e,'A-1').id);execute(e,'Crée une commande urgente de 5 Coca-Cola depuis A-1.');expect(e.state.orders[0]).toMatchObject({sku:'COCA',quantity:5,priority:3,sourceId:shelf(e,'A-1').id});const old=JSON.parse(e.serialize());old.robots.forEach((r:Record<string,unknown>)=>delete r.allowedProducts);expect(()=>Engine.restore(JSON.stringify(old))).not.toThrow();old.robots[0].allowedProducts=['MISSING'];expect(()=>Engine.restore(JSON.stringify(old))).toThrow();});
});
describe('contextual multi-incident laboratory',()=>{
 it('tracks separate failures, charges repair once and derives resolution from live state',()=>{const e=setup(),records:LabIncident[]=[],r=e.state.robots[0],r2=e.state.robots[1];expect(applyLabIncident(e,'Robot en panne',{target:r.id},records).ok).toBe(true);expect(applyLabIncident(e,'Batterie critique',{target:r2.id,battery:7},records).ok).toBe(true);expect(records).toHaveLength(2);expect(incidentResolved(e,records[0])).toBe(false);const budget=e.state.budget;e.repairRobot(r.id);expect(e.state.budget).toBe(budget-PRICES.repair);expect(incidentResolved(e,records[0])).toBe(true);expect(incidentResolved(e,records[1])).toBe(false);expect(e.repairRobot(r.id).ok).toBe(false);expect(e.state.budget).toBe(budget-PRICES.repair);});
 it('places and removes a real chosen obstacle, rejecting occupied cells without mutations',()=>{const e=setup(),records:LabIncident[]=[];expect(applyLabIncident(e,'Passage bloqué',{cell:{x:0,y:0}},records).ok).toBe(true);expect(incidentResolved(e,records[0])).toBe(false);const t=e.state.tiles.find(t=>records[0].walls.includes(t.id))!;expect(t.kind).toBe('wall');const before=e.serialize();expect(applyLabIncident(e,'Passage bloqué',{cell:{x:0,y:0}},records).ok).toBe(false);expect(e.serialize()).toBe(before);expect(records).toHaveLength(1);e.removeAt(0,0);expect(incidentResolved(e,records[0])).toBe(true);});
 it('removes only available stock, protects reservations and diagnoses the affected order',()=>{const e=setup(),records:LabIncident[]=[],t=shelf(e,'A-1');stockOperation(e,'COCA','Coca-Cola',10,t.id);e.createOrder('COCA',5,3,{sourceId:t.id});e.tick();const reserved=e.stockInfo(t).reserved;expect(reserved).toBeGreaterThan(0);expect(applyLabIncident(e,'Rupture de stock',{sku:'COCA'},records).ok).toBe(true);expect(t.stock).toBe(reserved);expect(e.stockInfo(t).available).toBe(0);expect(records[0].orders).toContain(e.state.orders[0].id);e.adjustStock(t.id,20);expect(incidentResolved(e,records[0])).toBe(true);});
 it('uses a real selected recharge station, queues robots and restores the exact baseline',()=>{const e=setup(),baseline=e.serialize(),records:LabIncident[]=[],station=e.state.tiles.find(t=>t.kind==='charger')!;expect(applyLabIncident(e,'Station saturée',{target:station.id},records).ok).toBe(true);expect(e.state.tiles.filter(t=>t.kind==='charger').map(t=>t.id)).toEqual([station.id]);expect(e.state.robots.filter(r=>r.state==='to-charge').length).toBeGreaterThan(1);for(let i=0;i<35;i++)e.tick();expect(e.state.robots.some(r=>r.state==='charging')).toBe(true);expect(e.state.robots.filter(r=>r.state==='waiting'||r.state==='to-charge').length).toBeGreaterThan(0);expect(Engine.restore(baseline).serialize()).toBe(baseline);});
 it('rejects invalid parameters and bounds active incidents without false successful records',()=>{const e=setup(),records:LabIncident[]=[],before=e.serialize();expect(applyLabIncident(e,'Commandes massives',{count:0},records).ok).toBe(false);expect(applyLabIncident(e,'Batterie critique',{target:e.state.robots[0].id,battery:40},records).ok).toBe(false);expect(e.serialize()).toBe(before);expect(records).toHaveLength(0);for(let x=0;x<12;x++)expect(applyLabIncident(e,'Passage bloqué',{cell:{x,y:0}},records).ok).toBe(true);const full=e.serialize();expect(applyLabIncident(e,'Passage bloqué',{cell:{x:12,y:0}},records).ok).toBe(false);expect(e.serialize()).toBe(full);expect(records).toHaveLength(12);});
});

